export type PteTriValue = "S" | "N" | "NA";

export type PteOfficialItem = {
  key: string;
  label: string;
};

export const PTE_RISCOS_POTENCIAIS: readonly PteOfficialItem[] = [
  { key: "projecao_particulas", label: "Projeção de partículas" },
  { key: "produtos_inflamaveis", label: "Produtos inflamáveis" },
  { key: "choque_eletrico", label: "Choque elétrico" },
  { key: "ruido_excessivo", label: "Ruído excessivo" },
  { key: "queda_diferenca_nivel", label: "Queda diferença nível / trabalho em altura" },
  { key: "piso_escorregadio", label: "Piso escorregadio" },
  { key: "contato_quimico_pele", label: "Contato de produto químico com a pele / corrosivos / tóxicos" },
  { key: "postura_inadequada", label: "Postura inadequada / esforço excessivo" },
  { key: "vapores_organicos", label: "Concentração de vapores orgânicos — incêndio e explosão" },
  { key: "trabalho_sobre_telhado", label: "Trabalho sobre telhado" },
  { key: "trabalho_eletrico_areas_classificadas", label: "Trabalho elétrico em áreas classificadas" },
  { key: "contato_cantos_vivos", label: "Contato com ferramentas/equipamentos/peças com cantos vivos ou rebarbas" },
  { key: "risco_queimadura", label: "Risco de queimadura" },
  { key: "levantamento_peso", label: "Levantamento/transporte de peso" },
  { key: "queda_pta", label: "Queda de PTA" },
  { key: "demolicao", label: "Demolição" },
  { key: "escavacao_desmoronamento", label: "Escavação/desmoronamento" },
  { key: "queda_escada", label: "Queda de escada" },
  { key: "queda_andaimes", label: "Queda de andaimes" },
  { key: "radiacao_nao_ionizante", label: "Radiação não ionizante" },
  { key: "fumos_metalicos", label: "Exposição a fumos metálicos" },
  { key: "trabalho_quente_faiscas", label: "Trabalho a quente — projeção de faíscas em áreas com risco de explosão" },
  { key: "manuseio_inflamaveis", label: "Manuseio de produtos inflamáveis (fogo/explosões)" },
  { key: "prensamento_membros", label: "Prensamento de membros" },
  { key: "animais_peconhentos", label: "Animais peçonhentos" },
  { key: "tubulacao_cabos_enterrados", label: "Tubulação e cabos enterrados" },
  { key: "uso_inadequado_ferramentas", label: "Uso inadequado de ferramentas e materiais" },
  { key: "explosao_incendio", label: "Explosão/incêndio" },
  { key: "exposicao_poeiras", label: "Exposição a poeiras" },
  { key: "exposicao_gases_vapores", label: "Exposição a gases e vapores" },
  { key: "manuseio_equipamento_guindar", label: "Manuseio de equipamento de guindar" },
  { key: "movimentacao_maquinas", label: "Movimentação de máquinas" },
  { key: "espaco_confinado", label: "Trabalho em espaço confinado" },
  { key: "expor_terceiros", label: "Expor terceiros a perigos" },
  { key: "desmoronamento_soterramento", label: "Desmoronamento/soterramento" },
  { key: "condicoes_climaticas", label: "Condições climáticas desfavoráveis" },
  { key: "superficie_arestas", label: "Superfície/arestas perfurocortantes" },
  { key: "radiacao_solar", label: "Exposição à radiação solar / trabalho a céu aberto" },
  { key: "outros", label: "Outros" },
] as const;

export const PTE_PREENCIMENTO_SNNA: readonly PteOfficialItem[] = [
  { key: "local_limpo_sinalizado", label: "O local de trabalho está limpo, organizado e sinalizado?" },
  { key: "equipe_conhece_emergencia", label: "A equipe envolvida conhece o sistema de emergência do local da atividade?" },
  { key: "rotas_fuga", label: "As rotas de fuga estão sinalizadas e desobstruídas?" },
  { key: "local_isolado", label: "O local foi isolado e sinalizado para limitar/impedir o acesso?" },
  { key: "ca_epi_validos", label: "CA dos EPI’s estão válidos e visíveis?" },
  { key: "apr_elaborada_entregue", label: "APR desse serviço foi elaborada/entregue?" },
  { key: "ambiente_protegido_vazamento", label: "O ambiente está protegido contra vazamento?" },
  { key: "trabalhadores_area_protegidos", label: "Os trabalhadores da área estão protegidos contra vazamentos?" },
  { key: "equipamentos_inspecionados", label: "Os equipamentos que serão usados foram inspecionados e estão perfeitos para uso?" },
  { key: "fontes_energia_bloqueadas", label: "As fontes de energia estão desligadas e bloqueadas?" },
  { key: "documentacoes_terceiros", label: "Foi checado as documentações de terceiros?" },
  { key: "outros", label: "Outros" },
] as const;

export const PTE_PRECAUCOES_QUENTE: readonly PteOfficialItem[] = [
  { key: "materiais_combustiveis_controlados", label: "Materiais/gases combustíveis ausentes ou controlados no raio de 11 m?" },
  { key: "cenario_incendio_protegido", label: "Cenário de prevenção e combate a incêndio protegido adequadamente?" },
  { key: "cilindros_oxiacetileno_valvulas", label: "Cilindros de oxiacetileno possuem válvulas contra retrocesso de chama?" },
  { key: "brigada_habilitada", label: "Equipe de brigada habilitada/capacitada para combate a incêndio?" },
  { key: "cilindros_manometro", label: "Cilindros de gases possuem manômetro/reguladores de pressão?" },
  { key: "acendedor_macarico", label: "Acender somente com acendedor de maçarico?" },
  { key: "recipientes_purgados", label: "Recipientes e tubulações purgados de líquidos/vapores inflamáveis?" },
  { key: "equipamentos_boas_condicoes", label: "Equipamentos de trabalho a quente em boas condições?" },
  { key: "cilindros_vertical_seguro", label: "Cilindros na vertical, amarrados, em local seguro e afastados de combustíveis?" },
  { key: "fispq_solda", label: "Existe FISPQ do material de solda?" },
  { key: "epis_quente_adequados", label: "EPI’s para trabalho a quente adequados?" },
  { key: "executante_qualificado", label: "Executante qualificado e certificado para realizar a atividade?" },
  { key: "vigilancia_incendio_presente", label: "Local avaliado pela vigilância de incêndio, presente durante a atividade?" },
  { key: "local_limpo_sem_combustiveis", label: "Local limpo, sem fiapos/plásticos/poeiras/materiais combustíveis?" },
  { key: "iluminacao_prova_explosao", label: "Utilizar iluminação à prova de explosão para espaço confinado?" },
  { key: "sprinklers_funcionando", label: "Sprinklers, hidrantes e extintores disponíveis estão funcionando?" },
  { key: "teste_explosimetro", label: "Foi realizado teste de explosímetro para vapores inflamáveis?" },
] as const;

export const PTE_PRECAUCOES_ALTURA: readonly PteOfficialItem[] = [
  { key: "condicoes_atmosfericas", label: "Condições atmosféricas favoráveis?" },
  { key: "escadas_andaime_boas_condicoes", label: "Escadas/andaimes em boas condições de segurança?" },
  { key: "envolvidos_condicoes_fisicas", label: "Envolvidos em boas condições físicas e psicológicas?" },
  { key: "estabilidade_andaimes", label: "Verificadas estabilidade/travamento de andaimes e escadas?" },
  { key: "segunda_pessoa", label: "Há necessidade de segunda pessoa para realizar a atividade?" },
  { key: "nr35_autorizados", label: "Executantes capacitados na NR-35 e autorizados?" },
  { key: "iluminacao_suficiente", label: "Iluminação suficiente para a atividade?" },
  { key: "itens_seg_pta", label: "Itens de segurança PTA adequados?" },
  { key: "escadas_amarradas", label: "Escadas amarradas, com pé antiderrapante e em boas condições?" },
  { key: "andaimes_rodas_travados", label: "Andaimes com rodas/elementos travados e forração completa?" },
  { key: "fixar_pranchoes", label: "Fixar pranchões ou passarelas em trabalhos no telhado?" },
  { key: "pontos_ancoragem", label: "Há pontos de ancoragem adequados?" },
  { key: "afastados_rede_eletrica", label: "Andaimes/plataformas/escadas afastados da rede elétrica?" },
  { key: "equipamentos_prevencao_queda", label: "Equipamentos de prevenção de queda adequados e perfeitos?" },
  { key: "telhas_sem_umidade", label: "Telhas isentas de umidade/perigo?" },
  { key: "andaimes_ancorados", label: "Andaimes ancorados, com sapatas, inspecionados e aprovados?" },
  { key: "area_abaixo_isolada", label: "Área abaixo do serviço isolada?" },
  { key: "escada_acesso_guarda_corpo", label: "Há escada de acesso, guarda-corpo e rodapé?" },
  { key: "clima_area_externa", label: "Trabalho externo com condições climáticas favoráveis?" },
  { key: "plano_resgate", label: "Existe plano de resgate?" },
] as const;

export const PTE_PRECAUCOES_ELETRICA: readonly PteOfficialItem[] = [
  { key: "fontes_desenergizadas", label: "As fontes de energia estão desenergizadas?" },
  { key: "fontes_bloqueadas", label: "Fontes/válvulas/equipamentos de energia bloqueados?" },
  { key: "teste_ausencia_tensao", label: "Foi realizado teste de ausência de tensão?" },
  { key: "sinalizada_fonte", label: "Fonte sinalizada com etiqueta/cartão de advertência do responsável?" },
  { key: "roupas_obrigatorias", label: "Eletricistas usando roupas obrigatórias para partes elétricas?" },
  { key: "recomendacoes_seccionamento", label: "Recomendações de Seccionamento de Fontes de Energia tomadas?" },
  { key: "nr10_sep_autorizados", label: "Executantes capacitados na NR-10/SEP e autorizados?" },
  { key: "paineis_bloqueados", label: "Painéis com bloqueio/travamento/sinalização/identificação?" },
  { key: "local_condicoes_ideais", label: "Local de trabalho em condições ideais para execução?" },
  { key: "equipamentos_aterrados", label: "Equipamentos e estruturas ao redor aterrados?" },
  { key: "dois_eletricistas", label: "Trabalhos elétricos sempre com dois eletricistas?" },
  { key: "materiais_metalicos_afastados", label: "Materiais metálicos afastados de redes energizadas?" },
  { key: "portas_subestacao_abertas", label: "Portas da subestação abertas durante atividade?" },
  { key: "livre_energia_residual", label: "Sistema livre de energia residual e com bloqueios aplicados?" },
  { key: "chave_geral_bloqueada", label: "Chave geral com manopla externa desligada/bloqueada?" },
  { key: "ferramentas_isolamento", label: "Ferramentas/equipamentos possuem isolamento elétrico?" },
  { key: "iluminacao_suficiente", label: "Existe iluminação suficiente no local?" },
] as const;

export const PTE_PRECAUCOES_CARGA: readonly PteOfficialItem[] = [
  { key: "isolamento_perimetro", label: "Foi realizado isolamento e sinalização no perímetro do içamento de carga?" },
  { key: "nao_passar_sob_cargas", label: "Não ficar ou passar embaixo de cargas suspensas." },
  { key: "piso_patolamento", label: "O piso está adequado para patolagem do guindaste ou munk?" },
  { key: "check_list_equipamentos", label: "Foi aplicado o check list dos equipamentos a serem usados no içamento?" },
  { key: "dispositivos_movimentacao", label: "Manter dispositivos de movimentação de material em condições adequadas." },
  { key: "corda_guia", label: "Foi instalada corda-guia ou dispositivo para auxiliar na movimentação?" },
  { key: "plano_rigging_5t", label: "Foi realizado plano de rigging e ART para içamento de carga acima de 5 toneladas?" },
  { key: "operador_habilitado", label: "O operador possui habilidade e tem conhecimento para realizar o içamento?" },
  { key: "operador_identificacao", label: "O operador possui identificação? Treinamentos obrigatórios?" },
  { key: "comunicacao_sinaleiro_operador", label: "No momento do içamento existe comunicação adequada entre sinaleiro e operador?" },
  { key: "velocidade_via", label: "Dirigir em velocidade adequada às condições da via." },
  { key: "equipamentos_acessorios_icamento", label: "Foram inspecionados e aprovados todos os equipamentos e acessórios de içamento?" },
] as const;

export const PTE_PRECAUCOES_PINTURA: readonly PteOfficialItem[] = [
  { key: "capacitado_pintura", label: "O colaborador está devidamente capacitado para trabalhar no processo de pintura?" },
  { key: "fispq_disponivel", label: "A FISPQ está à disposição e há treinamento quanto ao manuseio dos produtos químicos?" },
  { key: "ventilacao_lie", label: "Ao término do serviço, a ventilação foi mantida e a concentração de gases avaliada em conformidade com o LIE?" },
  { key: "equipamentos_prova_explosao", label: "Está sendo utilizado equipamento e iluminação à prova de explosão em espaço confinado?" },
  { key: "analisar_ambiente", label: "Analisar o ambiente antes de iniciar o trabalho." },
  { key: "area_sinalizada", label: "A área foi devidamente sinalizada, demarcada e isolada?" },
  { key: "bomba_aterrada", label: "A bomba utilizada no sistema de pistola pneumática está devidamente aterrada?" },
  { key: "cabos_sem_emendas", label: "Os cabos de alimentação elétrica estão sem emendas no processo de pintura (Airless)?" },
  { key: "sem_trabalho_quente", label: "Não existe nenhum trabalho a quente no local onde está sendo realizado o processo de pintura?" },
  { key: "bomba_fora_confinado", label: "A bomba pneumática de pintura (Airless) está instalada fora do espaço confinado?" },
  { key: "fogo_afastado", label: "Manter fogo e faíscas afastados de inflamáveis." },
  { key: "sem_servico_incompativel", label: "No local de trabalho não há serviço incompatível nas adjacências?" },
] as const;

/** EPIs — coluna 1 do PDF (Óculos, Capacete, Respiradores, Botas). */
export const PTE_EPIS_1: readonly PteOfficialItem[] = [
  { key: "oculos_incolor", label: "Óculos de Segurança Incolor" },
  { key: "oculos_escuro", label: "Óculos de segurança lente escura" },
  { key: "oculos_ton5", label: "Óculos de segurança Ton. 5" },
  { key: "capacete", label: "Capacete" },
  { key: "capacete_eletricista", label: "Capacete para eletricista" },
  { key: "capacete_jugular_altura", label: "Capacete com jugular — trabalho em altura" },
  { key: "protetor_viseira_facial", label: "Protetor ou Viseira Facial" },
  { key: "mascara_solda", label: "Máscara de solda" },
  { key: "protetor_auricular_plug", label: "Protetor Auricular Plug" },
  { key: "protetor_auricular_concha", label: "Protetor Auricular Concha" },
  { key: "respirador_poeiras", label: "Respirador para poeiras, névoas e fumos" },
  { key: "respirador_vapores", label: "Respirador para vapores químicos" },
  { key: "respirador_gases_acidos", label: "Respiradores para gases ácidos" },
  { key: "respirador_filtros_combinados", label: "Respirador com filtros combinados" },
  { key: "uniforme_eletricista", label: "Uniforme para eletricista" },
  { key: "bota_pvc", label: "Bota de PVC (7 léguas)" },
  { key: "bota_seguranca", label: "Bota de segurança" },
] as const;

/** EPIs — coluna 2 do PDF (Botas específicas, Aventais, Mangotes, Macacões, Luvas). */
export const PTE_EPIS_2: readonly PteOfficialItem[] = [
  { key: "bota_eletricista", label: "Bota de eletricista" },
  { key: "avental_raspa", label: "Avental de raspa" },
  { key: "avental_pvc", label: "Avental de PVC" },
  { key: "mangote_raspa", label: "Mangote raspa" },
  { key: "macacao_tyvec", label: "Macacão de tyvec" },
  { key: "macacao_pintor", label: "Macacão de pintor" },
  { key: "luva_nitrilica", label: "Luva Nitrílica" },
  { key: "luva_latex", label: "Luva Látex" },
  { key: "luva_pvc", label: "Luva PVC" },
  { key: "luva_malha", label: "Luva Malha" },
  { key: "luva_vaqueta", label: "Luva Vaqueta" },
  { key: "luva_raspa", label: "Luva Raspa" },
  { key: "luva_isolante_cl2", label: "Luva Isolante Classe 2" },
  { key: "cinto_paraquedista", label: "Cinto tipo Paraquedista" },
  { key: "talabarte", label: "Talabarte Y ou 2 talabartes" },
  { key: "perneira_raspa", label: "Perneira Raspa" },
] as const;

/** OUTROS — coluna 3 do PDF (Coletivos, isolamentos, sinalização). */
export const PTE_OUTROS_EPI: readonly PteOfficialItem[] = [
  { key: "guarda_corpo", label: "Guarda Corpo" },
  { key: "linha_vida_movel", label: "Linha de Vida Móvel" },
  { key: "linha_vida_fixa", label: "Linha de Vida Fixa" },
  { key: "placas_sinalizacao", label: "Placas Sinalização" },
  { key: "isolamento_area", label: "Isolamento de Área" },
  { key: "tapume_solda", label: "Tapume para solda" },
  { key: "tapete_isolante", label: "Tapete Isolante" },
  { key: "coberturas_isolantes", label: "Coberturas Isolantes" },
  { key: "conjunto_ferramentas_isoladas", label: "Conjunto Ferramentas Isoladas" },
  { key: "cones_sinalizacao", label: "Cones Sinalização" },
  { key: "fitas_sinalizacao", label: "Fitas Sinalização" },
  { key: "escoramento", label: "Escoramento" },
  { key: "tapumes", label: "Tapumes" },
  { key: "sem_adornos", label: "Colaborador sem adornos (brincos, correntes, anéis, relógios etc.)" },
  { key: "lanternas_seguras", label: "Lanternas intrinsecamente seguras" },
  { key: "outros", label: "Outros" },
] as const;