export type PteTriValue = "S" | "N" | "NA";

export type PteOfficialItem = {
  key: string;
  label: string;
};

export const PTE_RISCOS_POTENCIAIS: readonly PteOfficialItem[] = [
  { key: "projecao_particulas", label: "Projeção de partículas" },
  { key: "produtos_inflamaveis", label: "Produtos inflamáveis" },
  { key: "choque_eletrico", label: "Choque elétrico" },
  { key: "ruido_excessivo", label: "Ruído excessivo" },
  { key: "queda_diferenca_nivel", label: "Queda diferença nível / trabalho em altura" },
  { key: "piso_escorregadio", label: "Piso escorregadio" },
  { key: "contato_quimico_pele", label: "Contato de produto químico com a pele / corrosivos / tóxicos" },
  { key: "postura_inadequada", label: "Postura inadequada / esforço excessivo" },
  { key: "vapores_organicos", label: "Concentração de vapores orgânicos — incêndio e explosão" },
  { key: "trabalho_sobre_telhado", label: "Trabalho sobre telhado" },
  { key: "trabalho_eletrico_areas_classificadas", label: "Trabalho elétrico em áreas classificadas" },
  { key: "contato_cantos_vivos", label: "Contato com ferramentas/equipamentos/peças com cantos vivos ou rebarbas" },
  { key: "risco_queimadura", label: "Risco de queimadura" },
  { key: "levantamento_peso", label: "Levantamento/transporte de peso" },
  { key: "queda_pta", label: "Queda de PTA" },
  { key: "demolicao", label: "Demolição" },
  { key: "escavacao_desmoronamento", label: "Escavação/desmoronamento" },
  { key: "queda_escada", label: "Queda de escada" },
  { key: "queda_andaimes", label: "Queda de andaimes" },
  { key: "radiacao_nao_ionizante", label: "Radiação não ionizante" },
  { key: "fumos_metalicos", label: "Exposição a fumos metálicos" },
  { key: "trabalho_quente_faiscas", label: "Trabalho a quente — projeção de faíscas em áreas com risco de explosão" },
  { key: "manuseio_inflamaveis", label: "Manuseio de produtos inflamáveis (fogo/explosões)" },
  { key: "prensamento_membros", label: "Prensamento de membros" },
  { key: "animais_peconhentos", label: "Animais peçonhentos" },
  { key: "tubulacao_cabos_enterrados", label: "Tubulação e cabos enterrados" },
  { key: "uso_inadequado_ferramentas", label: "Uso inadequado de ferramentas e materiais" },
  { key: "explosao_incendio", label: "Explosão/incêndio" },
  { key: "exposicao_poeiras", label: "Exposição a poeiras" },
  { key: "exposicao_gases_vapores", label: "Exposição a gases e vapores" },
  { key: "manuseio_equipamento_guindar", label: "Manuseio de equipamento de guindar" },
  { key: "movimentacao_maquinas", label: "Movimentação de máquinas" },
  { key: "espaco_confinado", label: "Trabalho em espaço confinado" },
  { key: "expor_terceiros", label: "Expor terceiros a perigos" },
  { key: "desmoronamento_soterramento", label: "Desmoronamento/soterramento" },
  { key: "condicoes_climaticas", label: "Condições climáticas desfavoráveis" },
  { key: "superficie_arestas", label: "Superfície/arestas perfurocortantes" },
  { key: "radiacao_solar", label: "Exposição à radiação solar / trabalho a céu aberto" },
  { key: "outros", label: "Outros" },
] as const;

export const PTE_PREENCIMENTO_SNNA: readonly PteOfficialItem[] = [
  { key: "local_limpo_sinalizado", label: "O local de trabalho está limpo, organizado e sinalizado?" },
  { key: "equipe_conhece_emergencia", label: "A equipe envolvida conhece o sistema de emergência do local da atividade?" },
  { key: "rotas_fuga", label: "As rotas de fuga estão sinalizadas e desobstruídas?" },
  { key: "local_isolado", label: "O local foi isolado e sinalizado para limitar/impedir o acesso?" },
  { key: "ca_epi_validos", label: "CA dos EPI’s estão válidos e visíveis?" },
  { key: "apr_elaborada_entregue", label: "APR desse serviço foi elaborada/entregue?" },
  { key: "ambiente_protegido_vazamento", label: "O ambiente está protegido contra vazamento?" },
  { key: "trabalhadores_area_protegidos", label: "Os trabalhadores da área estão protegidos contra vazamentos?" },
  { key: "equipamentos_inspecionados", label: "Os equipamentos que serão usados foram inspecionados e estão perfeitos para uso?" },
  { key: "fontes_energia_bloqueadas", label: "As fontes de energia estão desligadas e bloqueadas?" },
  { key: "documentacoes_terceiros", label: "Foi checado as documentações de terceiros?" },
  { key: "outros", label: "Outros" },
] as const;

export const PTE_PRECAUCOES_QUENTE: readonly PteOfficialItem[] = [
  { key: "materiais_combustiveis_controlados", label: "Materiais/gases combustíveis ausentes ou controlados no raio de 11 m?" },
  { key: "cenario_incendio_protegido", label: "Cenário de prevenção e combate a incêndio protegido adequadamente?" },
  { key: "cilindros_oxiacetileno_valvulas", label: "Cilindros de oxiacetileno possuem válvulas contra retrocesso de chama?" },
  { key: "brigada_habilitada", label: "Equipe de brigada habilitada/capacitada para combate a incêndio?" },
  { key: "cilindros_manometro", label: "Cilindros de gases possuem manômetro/reguladores de pressão?" },
  { key: "acendedor_macarico", label: "Acender somente com acendedor de maçarico?" },
  { key: "recipientes_purgados", label: "Recipientes e tubulações purgados de líquidos/vapores inflamáveis?" },
  { key: "equipamentos_boas_condicoes", label: "Equipamentos de trabalho a quente em boas condições?" },
  { key: "cilindros_vertical_seguro", label: "Cilindros na vertical, amarrados, em local seguro e afastados de combustíveis?" },
  { key: "fispq_solda", label: "Existe FISPQ do material de solda?" },
  { key: "epis_quente_adequados", label: "EPI’s para trabalho a quente adequados?" },
  { key: "executante_qualificado", label: "Executante qualificado e certificado para realizar a atividade?" },
  { key: "vigilancia_incendio_presente", label: "Local avaliado pela vigilância de incêndio, presente durante a atividade?" },
  { key: "local_limpo_sem_combustiveis", label: "Local limpo, sem fiapos/plásticos/poeiras/materiais combustíveis?" },
  { key: "iluminacao_prova_explosao", label: "Utilizar iluminação à prova de explosão para espaço confinado?" },
  { key: "sprinklers_funcionando", label: "Sprinklers, hidrantes e extintores disponíveis estão funcionando?" },
  { key: "teste_explosimetro", label: "Foi realizado teste de explosímetro para vapores inflamáveis?" },
] as const;

export const PTE_PRECAUCOES_ALTURA: readonly PteOfficialItem[] = [
  { key: "condicoes_atmosfericas", label: "Condições atmosféricas favoráveis?" },
  { key: "escadas_andaime_boas_condicoes", label: "Escadas/andaimes em boas condições de segurança?" },
  { key: "envolvidos_condicoes_fisicas", label: "Envolvidos em boas condições físicas e psicológicas?" },
  { key: "estabilidade_andaimes", label: "Verificadas estabilidade/travamento de andaimes e escadas?" },
  { key: "segunda_pessoa", label: "Há necessidade de segunda pessoa para realizar a atividade?" },
  { key: "nr35_autorizados", label: "Executantes capacitados na NR-35 e autorizados?" },
  { key: "iluminacao_suficiente", label: "Iluminação suficiente para a atividade?" },
  { key: "itens_seg_pta", label: "Itens de segurança PTA adequados?" },
  { key: "escadas_amarradas", label: "Escadas amarradas, com pé antiderrapante e em boas condições?" },
  { key: "andaimes_rodas_travados", label: "Andaimes com rodas/elementos travados e forração completa?" },
  { key: "fixar_pranchoes", label: "Fixar pranchões ou passarelas em trabalhos no telhado?" },
  { key: "pontos_ancoragem", label: "Há pontos de ancoragem adequados?" },
  { key: "afastados_rede_eletrica", label: "Andaimes/plataformas/escadas afastados da rede elétrica?" },
  { key: "equipamentos_prevencao_queda", label: "Equipamentos de prevenção de queda adequados e perfeitos?" },
  { key: "telhas_sem_umidade", label: "Telhas isentas de umidade/perigo?" },
  { key: "andaimes_ancorados", label: "Andaimes ancorados, com sapatas, inspecionados e aprovados?" },
  { key: "area_abaixo_isolada", label: "Área abaixo do serviço isolada?" },
  { key: "escada_acesso_guarda_corpo", label: "Há escada de acesso, guarda-corpo e rodapé?" },
  { key: "clima_area_externa", label: "Trabalho externo com condições climáticas favoráveis?" },
  { key: "plano_resgate", label: "Existe plano de resgate?" },
] as const;

export const PTE_PRECAUCOES_ELETRICA: readonly PteOfficialItem[] = [
  { key: "fontes_desenergizadas", label: "As fontes de energia estão desenergizadas?" },
  { key: "fontes_bloqueadas", label: "Fontes/válvulas/equipamentos de energia bloqueados?" },
  { key: "teste_ausencia_tensao", label: "Foi realizado teste de ausência de tensão?" },
  { key: "sinalizada_fonte", label: "Fonte sinalizada com etiqueta/cartão de advertência do responsável?" },
  { key: "roupas_obrigatorias", label: "Eletricistas usando roupas obrigatórias para partes elétricas?" },
  { key: "recomendacoes_seccionamento", label: "Recomendações de Seccionamento de Fontes de Energia tomadas?" },
  { key: "nr10_sep_autorizados", label: "Executantes capacitados na NR-10/SEP e autorizados?" },
  { key: "paineis_bloqueados", label: "Painéis com bloqueio/travamento/sinalização/identificação?" },
  { key: "local_condicoes_ideais", label: "Local de trabalho em condições ideais para execução?" },
  { key: "equipamentos_aterrados", label: "Equipamentos e estruturas ao redor aterrados?" },
  { key: "dois_eletricistas", label: "Trabalhos elétricos sempre com dois eletricistas?" },
  { key: "materiais_metalicos_afastados", label: "Materiais metálicos afastados de redes energizadas?" },
  { key: "portas_subestacao_abertas", label: "Portas da subestação abertas durante atividade?" },
  { key: "livre_energia_residual", label: "Sistema livre de energia residual e com bloqueios aplicados?" },
  { key: "chave_geral_bloqueada", label: "Chave geral com manopla externa desligada/bloqueada?" },
  { key: "ferramentas_isolamento", label: "Ferramentas/equipamentos possuem isolamento elétrico?" },
  { key: "iluminacao_suficiente", label: "Existe iluminação suficiente no local?" },
] as const;