/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppRolesRouteImport } from './routes/app.roles'
import { Route as AppPtesRouteImport } from './routes/app.ptes'
import { Route as AppEmployeesRouteImport } from './routes/app.employees'
import { Route as AppCompaniesRouteImport } from './routes/app.companies'
import { Route as AppEmployeesIdRouteImport } from './routes/app.employees.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppPtesRoute = AppPtesRouteImport.update({
  id: '/ptes',
  path: '/ptes',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesRoute = AppCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesIdRoute = AppEmployeesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppEmployeesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/employees': typeof AppEmployeesRouteWithChildren
  '/app/ptes': typeof AppPtesRoute
  '/app/roles': typeof AppRolesRoute
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
  '/app/employees/$id': typeof AppEmployeesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/employees': typeof AppEmployeesRouteWithChildren
  '/app/ptes': typeof AppPtesRoute
  '/app/roles': typeof AppRolesRoute
  '/app/users': typeof AppUsersRoute
  '/app': typeof AppIndexRoute
  '/app/employees/$id': typeof AppEmployeesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/employees': typeof AppEmployeesRouteWithChildren
  '/app/ptes': typeof AppPtesRoute
  '/app/roles': typeof AppRolesRoute
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
  '/app/employees/$id': typeof AppEmployeesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/companies'
    | '/app/employees'
    | '/app/ptes'
    | '/app/roles'
    | '/app/users'
    | '/app/'
    | '/app/employees/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/companies'
    | '/app/employees'
    | '/app/ptes'
    | '/app/roles'
    | '/app/users'
    | '/app'
    | '/app/employees/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/companies'
    | '/app/employees'
    | '/app/ptes'
    | '/app/roles'
    | '/app/users'
    | '/app/'
    | '/app/employees/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/roles': {
      id: '/app/roles'
      path: '/roles'
      fullPath: '/app/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ptes': {
      id: '/app/ptes'
      path: '/ptes'
      fullPath: '/app/ptes'
      preLoaderRoute: typeof AppPtesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employees': {
      id: '/app/employees'
      path: '/employees'
      fullPath: '/app/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/companies': {
      id: '/app/companies'
      path: '/companies'
      fullPath: '/app/companies'
      preLoaderRoute: typeof AppCompaniesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employees/$id': {
      id: '/app/employees/$id'
      path: '/$id'
      fullPath: '/app/employees/$id'
      preLoaderRoute: typeof AppEmployeesIdRouteImport
      parentRoute: typeof AppEmployeesRoute
    }
  }
}

interface AppEmployeesRouteChildren {
  AppEmployeesIdRoute: typeof AppEmployeesIdRoute
}

const AppEmployeesRouteChildren: AppEmployeesRouteChildren = {
  AppEmployeesIdRoute: AppEmployeesIdRoute,
}

const AppEmployeesRouteWithChildren = AppEmployeesRoute._addFileChildren(
  AppEmployeesRouteChildren,
)

interface AppRouteChildren {
  AppCompaniesRoute: typeof AppCompaniesRoute
  AppEmployeesRoute: typeof AppEmployeesRouteWithChildren
  AppPtesRoute: typeof AppPtesRoute
  AppRolesRoute: typeof AppRolesRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCompaniesRoute: AppCompaniesRoute,
  AppEmployeesRoute: AppEmployeesRouteWithChildren,
  AppPtesRoute: AppPtesRoute,
  AppRolesRoute: AppRolesRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
