REVOKE EXECUTE ON FUNCTION public.oss_emissoes_before_insert() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.oss_marcar_vencidas() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.oss_on_employee_cargo_change() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.oss_on_template_revision_change() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.oss_templates_before_write() FROM PUBLIC, anon, authenticated;

REVOKE EXECUTE ON FUNCTION public.ajustar_saldo_epi(uuid, integer) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.current_aal() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.gerar_numero_apr() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.gerar_numero_controle_doc() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.gerar_numero_extintor() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.gerar_numero_ordem_producao() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.gerar_numero_tnc() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.has_module_access(uuid, public.app_module) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_editor(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_moderator(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_viewer_or_above(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.mfa_ok() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.peek_proximo_numero_apr() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.registrar_entrega_epi(uuid, text, text, integer) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.registrar_movimentacao_epi(uuid, integer, public.tipo_movimentacao_epi, text, text, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.requires_mfa(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.snapshot_estoque_epi_monthly() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.validar_eficacia_acao(uuid, boolean, text) FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.ajustar_saldo_epi(uuid, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.current_aal() TO authenticated;
GRANT EXECUTE ON FUNCTION public.gerar_numero_apr() TO authenticated;
GRANT EXECUTE ON FUNCTION public.gerar_numero_controle_doc() TO authenticated;
GRANT EXECUTE ON FUNCTION public.gerar_numero_extintor() TO authenticated;
GRANT EXECUTE ON FUNCTION public.gerar_numero_ordem_producao() TO authenticated;
GRANT EXECUTE ON FUNCTION public.gerar_numero_tnc() TO authenticated;
GRANT EXECUTE ON FUNCTION public.has_module_access(uuid, public.app_module) TO authenticated;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_editor(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_moderator(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_viewer_or_above(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mfa_ok() TO authenticated;
GRANT EXECUTE ON FUNCTION public.peek_proximo_numero_apr() TO authenticated;
GRANT EXECUTE ON FUNCTION public.registrar_entrega_epi(uuid, text, text, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.registrar_movimentacao_epi(uuid, integer, public.tipo_movimentacao_epi, text, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.requires_mfa(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.snapshot_estoque_epi_monthly() TO authenticated;
GRANT EXECUTE ON FUNCTION public.validar_eficacia_acao(uuid, boolean, text) TO authenticated;