
-- =========================================================
-- DDS (Diálogos Diários de Segurança) — Fase 1
-- =========================================================

-- 1) TEMAS
CREATE TABLE public.dds_temas (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  codigo INTEGER UNIQUE,
  titulo TEXT NOT NULL,
  categoria TEXT NOT NULL DEFAULT 'GERAL' CHECK (categoria IN ('SIGNIFICATIVO','GERAL')),
  criticidade TEXT NOT NULL DEFAULT 'MEDIA' CHECK (criticidade IN ('ALTA','MEDIA','BAIXA')),
  ativo BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE public.dds_temas ENABLE ROW LEVEL SECURITY;
CREATE POLICY dds_temas_select ON public.dds_temas FOR SELECT TO authenticated USING (true);
CREATE POLICY dds_temas_insert ON public.dds_temas FOR INSERT TO authenticated WITH CHECK (is_editor(auth.uid()));
CREATE POLICY dds_temas_update ON public.dds_temas FOR UPDATE TO authenticated USING (is_editor(auth.uid()));
CREATE POLICY dds_temas_delete ON public.dds_temas FOR DELETE TO authenticated USING (has_role(auth.uid(),'admin'::app_role));
CREATE TRIGGER trg_dds_temas_updated BEFORE UPDATE ON public.dds_temas FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- 2) GESTORES
CREATE TABLE public.dds_gestores (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nome TEXT NOT NULL,
  employee_id UUID NULL,
  setor TEXT,
  ativo BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE public.dds_gestores ENABLE ROW LEVEL SECURITY;
CREATE POLICY dds_gestores_select ON public.dds_gestores FOR SELECT TO authenticated USING (true);
CREATE POLICY dds_gestores_insert ON public.dds_gestores FOR INSERT TO authenticated WITH CHECK (is_editor(auth.uid()));
CREATE POLICY dds_gestores_update ON public.dds_gestores FOR UPDATE TO authenticated USING (is_editor(auth.uid()));
CREATE POLICY dds_gestores_delete ON public.dds_gestores FOR DELETE TO authenticated USING (has_role(auth.uid(),'admin'::app_role));
CREATE TRIGGER trg_dds_gestores_updated BEFORE UPDATE ON public.dds_gestores FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- 3) DDS
CREATE TABLE public.dds (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  data DATE NOT NULL DEFAULT CURRENT_DATE,
  hora TIME,
  gestor_id UUID REFERENCES public.dds_gestores(id) ON DELETE SET NULL,
  setor TEXT,
  tema_id UUID REFERENCES public.dds_temas(id) ON DELETE SET NULL,
  tema_livre TEXT,
  duracao_min INTEGER NOT NULL DEFAULT 10,
  conteudo TEXT,
  participantes_esperados INTEGER NOT NULL DEFAULT 0,
  participantes_presentes INTEGER NOT NULL DEFAULT 0,
  aderencia NUMERIC(5,2) GENERATED ALWAYS AS (
    CASE WHEN participantes_esperados > 0
      THEN ROUND((participantes_presentes::NUMERIC / participantes_esperados::NUMERIC) * 100, 2)
      ELSE 0 END
  ) STORED,
  status TEXT NOT NULL DEFAULT 'REALIZADO' CHECK (status IN ('REALIZADO','CANCELADO','PENDENTE')),
  incident_id UUID NULL,
  observacoes TEXT,
  created_by UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_dds_data ON public.dds(data DESC);
CREATE INDEX idx_dds_setor ON public.dds(setor);
CREATE INDEX idx_dds_gestor ON public.dds(gestor_id);
ALTER TABLE public.dds ENABLE ROW LEVEL SECURITY;
CREATE POLICY dds_select ON public.dds FOR SELECT TO authenticated USING (true);
CREATE POLICY dds_insert ON public.dds FOR INSERT TO authenticated WITH CHECK (is_editor(auth.uid()));
CREATE POLICY dds_update ON public.dds FOR UPDATE TO authenticated USING (is_editor(auth.uid()));
CREATE POLICY dds_delete ON public.dds FOR DELETE TO authenticated USING (has_role(auth.uid(),'admin'::app_role));
CREATE TRIGGER trg_dds_updated BEFORE UPDATE ON public.dds FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- 4) ATTENDEES
CREATE TABLE public.dds_attendees (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  dds_id UUID NOT NULL REFERENCES public.dds(id) ON DELETE CASCADE,
  employee_id UUID NOT NULL,
  status TEXT NOT NULL DEFAULT 'PRESENTE' CHECK (status IN ('PRESENTE','AUSENTE','JUSTIFICADO')),
  observacao TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(dds_id, employee_id)
);
CREATE INDEX idx_dds_att_dds ON public.dds_attendees(dds_id);
CREATE INDEX idx_dds_att_emp ON public.dds_attendees(employee_id);
ALTER TABLE public.dds_attendees ENABLE ROW LEVEL SECURITY;
CREATE POLICY dds_att_select ON public.dds_attendees FOR SELECT TO authenticated USING (true);
CREATE POLICY dds_att_insert ON public.dds_attendees FOR INSERT TO authenticated WITH CHECK (is_editor(auth.uid()));
CREATE POLICY dds_att_update ON public.dds_attendees FOR UPDATE TO authenticated USING (is_editor(auth.uid()));
CREATE POLICY dds_att_delete ON public.dds_attendees FOR DELETE TO authenticated USING (is_editor(auth.uid()));

-- 5) EVIDÊNCIAS
CREATE TABLE public.dds_evidencias (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  dds_id UUID NOT NULL REFERENCES public.dds(id) ON DELETE CASCADE,
  file_path TEXT NOT NULL,
  tipo TEXT,
  descricao TEXT,
  uploaded_by UUID,
  uploaded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE public.dds_evidencias ENABLE ROW LEVEL SECURITY;
CREATE POLICY dds_evid_select ON public.dds_evidencias FOR SELECT TO authenticated USING (true);
CREATE POLICY dds_evid_insert ON public.dds_evidencias FOR INSERT TO authenticated WITH CHECK (is_editor(auth.uid()));
CREATE POLICY dds_evid_update ON public.dds_evidencias FOR UPDATE TO authenticated USING (is_editor(auth.uid()));
CREATE POLICY dds_evid_delete ON public.dds_evidencias FOR DELETE TO authenticated USING (has_role(auth.uid(),'admin'::app_role));

-- 6) BUCKET
INSERT INTO storage.buckets (id, name, public) VALUES ('dds-anexos','dds-anexos', false)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "dds_anexos_select" ON storage.objects FOR SELECT TO authenticated
USING (bucket_id = 'dds-anexos');
CREATE POLICY "dds_anexos_insert" ON storage.objects FOR INSERT TO authenticated
WITH CHECK (bucket_id = 'dds-anexos' AND is_editor(auth.uid()));
CREATE POLICY "dds_anexos_update" ON storage.objects FOR UPDATE TO authenticated
USING (bucket_id = 'dds-anexos' AND is_editor(auth.uid()));
CREATE POLICY "dds_anexos_delete" ON storage.objects FOR DELETE TO authenticated
USING (bucket_id = 'dds-anexos' AND has_role(auth.uid(),'admin'::app_role));

-- 7) SEED 120 TEMAS (do PDF DMN ESTALEIRO)
INSERT INTO public.dds_temas (codigo, titulo, categoria, criticidade) VALUES
(1,'LIXADEIRAS E ESMERILHADEIRAS','SIGNIFICATIVO','ALTA'),
(2,'MOVIMENTAÇÃO DE MATERIAIS','SIGNIFICATIVO','MEDIA'),
(3,'MANUTENÇÃO E USO DOS ÓCULOS DE SEGURANÇA','SIGNIFICATIVO','MEDIA'),
(4,'CAPACETE','SIGNIFICATIVO','MEDIA'),
(5,'CHOQUE ELÉTRICO','SIGNIFICATIVO','ALTA'),
(6,'CINTO DE SEGURANÇA','SIGNIFICATIVO','MEDIA'),
(7,'COLETA SELETIVA','SIGNIFICATIVO','BAIXA'),
(8,'COMBATE A INCÊNDIO','SIGNIFICATIVO','ALTA'),
(9,'CONDIÇÕES INSEGURAS','SIGNIFICATIVO','ALTA'),
(10,'CONDIÇÕES PERIGOSAS NO USO DE MAÇARICOS','SIGNIFICATIVO','ALTA'),
(11,'CONTROLE DO RUÍDO','SIGNIFICATIVO','MEDIA'),
(12,'CUIDADOS COM AR COMPRIMIDO','SIGNIFICATIVO','MEDIA'),
(13,'CUIDADOS COM CILINDROS DE GASES','SIGNIFICATIVO','ALTA'),
(14,'CUIDADOS COM A SAÚDE FÍSICA','SIGNIFICATIVO','BAIXA'),
(15,'EFEITOS DO RUÍDO NO HOMEM E SISTEMA AUDITIVO','SIGNIFICATIVO','MEDIA'),
(16,'EQUIPAMENTO DE PROTEÇÃO INDIVIDUAL – EPI','SIGNIFICATIVO','ALTA'),
(17,'FONES DE OUVIDO: USO INADEQUADO PODE CAUSAR PERDA AUDITIVA','SIGNIFICATIVO','MEDIA'),
(18,'INSPEÇÃO DAS FERRAMENTAS DE TRABALHO','SIGNIFICATIVO','MEDIA'),
(19,'LEVANTAMENTO DE PESOS','SIGNIFICATIVO','MEDIA'),
(20,'LEVANTAMENTO E TRANSPORTE MANUAL DE PESO','SIGNIFICATIVO','MEDIA'),
(21,'A IMPORTÂNCIA DA UTILIZAÇÃO DOS EPIs NO SERVIÇO DE MANUTENÇÃO','SIGNIFICATIVO','MEDIA'),
(22,'MOVIMENTAÇÃO DE MATERIAIS (II)','SIGNIFICATIVO','MEDIA'),
(23,'ORGANIZAÇÃO E LIMPEZA – ETAPA FINAL DO TRABALHO','SIGNIFICATIVO','BAIXA'),
(24,'PRIMEIROS SOCORROS','SIGNIFICATIVO','ALTA'),
(25,'PROTEÇÃO DAS MÃOS','SIGNIFICATIVO','MEDIA'),
(26,'PROTEÇÃO DOS OLHOS','SIGNIFICATIVO','MEDIA'),
(27,'PROTETOR AURICULAR','SIGNIFICATIVO','MEDIA'),
(28,'PROTETOR FACIAL','SIGNIFICATIVO','MEDIA'),
(29,'QUASE ACIDENTES SÃO SINAIS DE ALERTA','SIGNIFICATIVO','ALTA'),
(30,'SOLVENTES INFLAMÁVEIS — COMO MANUSEAR','SIGNIFICATIVO','ALTA'),
(31,'PREVENÇÃO DE ACIDENTES DE TRAJETO','SIGNIFICATIVO','MEDIA'),
(32,'ARRANJO FÍSICO','SIGNIFICATIVO','BAIXA'),
(33,'SEGURANÇA NA INDÚSTRIA NAVAL','SIGNIFICATIVO','ALTA'),
(34,'BLOQUEIO E ETIQUETAGEM','SIGNIFICATIVO','ALTA'),
(35,'LESÕES POR ESFORÇO REPETITIVO (LER)','SIGNIFICATIVO','MEDIA'),
(36,'SEGURANÇA EM MÁQUINAS E FERRAMENTAS','SIGNIFICATIVO','ALTA'),
(37,'SAÚDE MENTAL E BEM-ESTAR','SIGNIFICATIVO','MEDIA'),
(38,'TRABALHO EM ALTURA – FATOR DE QUEDA','SIGNIFICATIVO','ALTA'),
(39,'NR 33 — TRABALHO EM ESPAÇO CONFINADO / VIGIA / PTE','SIGNIFICATIVO','ALTA'),
(40,'CUIDADOS COM FERRAMENTAS ELÉTRICAS PORTÁTEIS','SIGNIFICATIVO','ALTA'),
(41,'ORDEM, LIMPEZA E ORGANIZAÇÃO (5S)','SIGNIFICATIVO','BAIXA'),
(42,'EDUCAÇÃO AMBIENTAL: PLANETA ÁGUA','SIGNIFICATIVO','BAIXA'),
(43,'BOTIJÃO DE GÁS','SIGNIFICATIVO','ALTA'),
(44,'TRABALHOS EM ALTURA SOBRE ANDAIME APOIADO','SIGNIFICATIVO','ALTA'),
(45,'EFEITOS CRÔNICOS DO ÁLCOOL','SIGNIFICATIVO','MEDIA'),
(46,'HEPATITE','SIGNIFICATIVO','MEDIA'),
(47,'RISCOS DA MÁ ILUMINAÇÃO NO LOCAL DE TRABALHO','SIGNIFICATIVO','MEDIA'),
(48,'CUIDADOS PARA EVITAR LESÃO NAS COSTAS','SIGNIFICATIVO','MEDIA'),
(49,'IMPROVISAÇÕES DE FERRAMENTAS OU USO INADEQUADO','SIGNIFICATIVO','ALTA'),
(50,'EQUIPAMENTO DE PROTEÇÃO COLETIVA – EPC','SIGNIFICATIVO','MEDIA'),
(51,'MOTIVACIONAL: VOCÊ É MAIOR QUE MEUS PROBLEMAS','SIGNIFICATIVO','BAIXA'),
(52,'TRABALHO EM EQUIPE','SIGNIFICATIVO','BAIXA'),
(53,'SOLDA MIG E TIG','SIGNIFICATIVO','ALTA'),
(54,'PERCEPÇÃO DE RISCO','SIGNIFICATIVO','ALTA'),
(55,'USO DE ADORNOS NO TRABALHO','SIGNIFICATIVO','MEDIA'),
(56,'RISCO NO PROCESSO DE SOLDAGEM','SIGNIFICATIVO','ALTA'),
(57,'PROTEÇÃO SOLAR NO TRABALHO','SIGNIFICATIVO','BAIXA'),
(58,'COMPORTAMENTOS DE RISCO','SIGNIFICATIVO','ALTA'),
(59,'CÂNCER DE PRÓSTATA','SIGNIFICATIVO','BAIXA'),
(60,'A IMPORTÂNCIA DO DESCANSO','SIGNIFICATIVO','BAIXA'),
(61,'DIREÇÃO DEFENSIVA','GERAL','MEDIA'),
(62,'NR 33 – TRABALHO EM ESPAÇO CONFINADO','GERAL','ALTA'),
(63,'FEBRE AMARELA','GERAL','BAIXA'),
(64,'LESÕES NAS COSTAS','GERAL','MEDIA'),
(65,'USO EXCESSIVO DE CELULAR','GERAL','MEDIA'),
(66,'DESCARTE DE RESÍDUOS','GERAL','MEDIA'),
(67,'ANÉIS, CORDÕES E PULSEIRAS','GERAL','MEDIA'),
(68,'O EXCESSO DE CONFIANÇA','GERAL','MEDIA'),
(69,'A IMPORTÂNCIA DO CINTO DE SEGURANÇA','GERAL','MEDIA'),
(70,'ATOS E CONDIÇÕES INSEGURAS','GERAL','ALTA'),
(71,'22 DE MARÇO – DIA DA ÁGUA','GERAL','BAIXA'),
(72,'FADIGA NO TRABALHO','GERAL','MEDIA'),
(73,'QUASE ACIDENTES','GERAL','ALTA'),
(74,'TRABALHO SEGURO','GERAL','MEDIA'),
(75,'27 DE JULHO: PREVENÇÃO DE ACIDENTE DO TRABALHO','GERAL','MEDIA'),
(76,'MAIO AMARELO – SEGURANÇA NO TRÂNSITO','GERAL','MEDIA'),
(77,'JUNHO VERMELHO – DOAR SANGUE SALVA VIDAS','GERAL','BAIXA'),
(78,'SETEMBRO AMARELO','GERAL','BAIXA'),
(79,'OUTUBRO ROSA','GERAL','BAIXA'),
(80,'ABRIL VERDE','GERAL','BAIXA'),
(81,'CUIDADO COM PRODUTOS QUÍMICOS','GERAL','ALTA'),
(82,'COMO AGIR EM CASO DE INCÊNDIO','GERAL','ALTA'),
(83,'DEPRESSÃO','GERAL','MEDIA'),
(84,'CAMPANHA NOVEMBRO AZUL','GERAL','BAIXA'),
(85,'DORT','GERAL','MEDIA'),
(86,'ERGONOMIA NO TRABALHO','GERAL','MEDIA'),
(87,'RISCO FÍSICO','GERAL','MEDIA'),
(88,'RISCO QUÍMICO','GERAL','ALTA'),
(89,'RISCO BIOLÓGICO','GERAL','MEDIA'),
(90,'RISCO ERGONÔMICO','GERAL','MEDIA'),
(91,'RISCO DE ACIDENTES','GERAL','ALTA'),
(92,'OS PERIGOS DA AUTOMEDICAÇÃO','GERAL','BAIXA'),
(93,'PREVENÇÃO – MELHOR FERRAMENTA DA SEGURANÇA','GERAL','MEDIA'),
(94,'TRABALHO COM CARGA SUSPENSA','GERAL','ALTA'),
(95,'COMPORTAMENTO POSITIVO NO LOCAL DE TRABALHO','GERAL','BAIXA'),
(96,'ALIMENTAÇÃO ADEQUADA','GERAL','BAIXA'),
(97,'RESPONSABILIDADE SOCIAL','GERAL','BAIXA'),
(98,'PAIR – PERDA AUDITIVA INDUZIDA POR RUÍDO','GERAL','MEDIA'),
(99,'TRABALHO SEGURO (II)','GERAL','MEDIA'),
(100,'ACIDENTES COM ANIMAIS PEÇONHENTOS','GERAL','MEDIA'),
(101,'ACIDENTES COM ELETRICIDADE','GERAL','ALTA'),
(102,'A IMPORTÂNCIA DA VACINAÇÃO','GERAL','BAIXA'),
(103,'AGOSTO LILÁS','GERAL','BAIXA'),
(104,'BRINCADEIRAS NO LOCAL DE TRABALHO','GERAL','MEDIA'),
(105,'CLASSES DO FOGO','GERAL','ALTA'),
(106,'A IMPORTÂNCIA DOS MEIOS DE COMBATE A INCÊNDIO','GERAL','ALTA'),
(107,'RESPEITO NO LOCAL DE TRABALHO','GERAL','BAIXA'),
(108,'SENSIBILIDADE INDIVIDUAL','GERAL','BAIXA'),
(109,'SAÚDE E SEGURANÇA ANDAM JUNTOS','GERAL','BAIXA'),
(110,'TRABALHO EM EQUIPE (II)','GERAL','BAIXA'),
(111,'PRINCÍPIOS DE UM BOM RELACIONAMENTO NO LOCAL DE TRABALHO','GERAL','BAIXA'),
(112,'A IMPORTÂNCIA DA HIDRATAÇÃO','GERAL','BAIXA'),
(113,'A IMPORTÂNCIA DA SINALIZAÇÃO NO LOCAL DE TRABALHO','GERAL','MEDIA'),
(114,'CUIDADOS COM A VISÃO E AUDIÇÃO','GERAL','MEDIA'),
(115,'A IMPORTÂNCIA DO SONO ADEQUADO','GERAL','BAIXA'),
(116,'VASOS DE PRESSÃO','GERAL','ALTA'),
(117,'MOVIMENTAÇÃO E ARMAZENAMENTO DE CARGAS','GERAL','ALTA'),
(118,'CUIDADOS NO PROCESSO DE IÇAMENTO DE CARGAS','GERAL','ALTA'),
(119,'TRABALHO A QUENTE','GERAL','ALTA'),
(120,'TRABALHO A CÉU ABERTO','GERAL','MEDIA');
