INSERT INTO public.catalogo_riscos (categoria, nome, efeitos_tipicos, medidas_controle_padrao, nrs_aplicaveis, epis_sugeridos)
SELECT * FROM (VALUES
('ACIDENTE_MECANICO','Injeção de fluido em alta pressão (hidrojateamento)',
 ARRAY['Injeção subcutânea de água','Laceração profunda','Amputação','Infecção grave/necrose'],
 ARRAY['Pistola com gatilho dead-man','Zona de exclusão sinalizada de no mínimo 10 m','Despressurização antes de qualquer intervenção','Operador certificado e exame médico específico','Inspeção de mangueiras e engates antes do uso'],
 ARRAY['NR-06','NR-12','NR-34'],
 ARRAY['Vestimenta anti-hidrojato','Luva anticorte de alta pressão','Capacete com viseira/protetor facial','Bota de segurança anti-hidrojato','Protetor auricular']),
('ACIDENTE_MECANICO','Coice/reação da pistola de hidrojato',
 ARRAY['Perda de controle do equipamento','Queda do operador','Lesão lombar e de ombro','Impacto contra terceiros'],
 ARRAY['Limitar força de reação a 1/3 do peso do operador','Uso de apoio/cinto de reação','Pausas programadas e rodízio','Piso antiderrapante e área desobstruída'],
 ARRAY['NR-12','NR-17','NR-34'],
 ARRAY['Vestimenta anti-hidrojato','Cinto de reação','Bota de segurança','Luva anticorte']),
('ACIDENTE_MECANICO','Atividades simultâneas (trabalhos sobrepostos)',
 ARRAY['Queda de objetos sobre terceiros','Exposição cruzada a fumos e faíscas','Choque entre equipes e equipamentos','Incêndio por serviço a quente próximo a inflamáveis'],
 ARRAY['Planejamento e liberação conjunta de PT/APR','Reunião diária de compatibilização de tarefas','Isolamento vertical e horizontal das frentes','Proibição de trabalho a quente abaixo/acima de outra frente','Vigia de área e comunicação por rádio'],
 ARRAY['NR-01','NR-18','NR-34','NR-35'],
 ARRAY['Capacete com jugular','Óculos de segurança','Protetor auricular','Bota de segurança']),
('FISICO','Descarga atmosférica / tempestade',
 ARRAY['Eletrocussão','Queimadura por arco','Queda por rajada de vento','Parada cardiorrespiratória'],
 ARRAY['Monitoramento meteorológico diário','Paralisação de trabalhos em altura e içamento com alerta de raios','Abrigo seguro definido e rota de evacuação','Aterramento de estruturas e equipamentos','Retomada somente 30 min após o último raio'],
 ARRAY['NR-01','NR-10','NR-34','NR-35'],
 ARRAY['Capacete com jugular','Bota de segurança','Capa de chuva']),
('FISICO','Exposição solar e calor a céu aberto',
 ARRAY['Insolação e exaustão térmica','Desidratação','Queimadura solar','Câncer de pele a longo prazo','Redução da atenção e erro operacional'],
 ARRAY['Pausas em local sombreado conforme IBUTG','Hidratação disponível na frente de serviço','Programação de tarefas críticas fora do pico térmico','Uso de tendas e barreiras de sombreamento','Treinamento de reconhecimento de sintomas'],
 ARRAY['NR-09','NR-15','NR-21'],
 ARRAY['Protetor solar FPS 30+','Camisa manga longa UV','Boné árabe sob capacete','Óculos de segurança com filtro UV']),
('ACIDENTE_MECANICO','Movimentação de máquinas e veículos no pátio',
 ARRAY['Atropelamento','Prensamento entre máquina e estrutura','Esmagamento de membros','Colisão e capotamento'],
 ARRAY['Rotas segregadas de pedestres e veículos','Sinaleiro/vigia em manobras e ponto cego','Alarme de ré e giroflex operantes','Limite de velocidade sinalizado no pátio','Operador habilitado e checklist pré-operacional'],
 ARRAY['NR-11','NR-12','NR-18'],
 ARRAY['Colete refletivo','Capacete com jugular','Bota de segurança','Óculos de segurança']),
('ACIDENTE_MECANICO','Queda de carga suspensa por falha de chapa/garra',
 ARRAY['Esmagamento fatal','Fratura múltipla','Amputação','Dano a estruturas e equipamentos'],
 ARRAY['Inspeção e certificação de garras, cabos e acessórios','Plano de rigging com cálculo de carga e ângulo','Isolamento total da área de projeção da carga','Proibição de circulação sob carga suspensa','Uso de cabo-guia para controle do balanço'],
 ARRAY['NR-11','NR-12','NR-34'],
 ARRAY['Capacete com jugular','Luva de vaqueta','Bota de segurança','Colete refletivo']),
('ACIDENTE_MECANICO','Energia residual por falta de bloqueio e etiquetagem (LOTO)',
 ARRAY['Choque elétrico','Partida inesperada de máquina','Amputação e esmagamento','Queimadura por fluido/vapor pressurizado'],
 ARRAY['Procedimento de bloqueio e etiquetagem com cadeado individual','Teste de energia zero antes da intervenção','Alívio de pressão e drenagem de linhas','Registro de bloqueio e liberação por responsável','Treinamento específico da equipe de manutenção'],
 ARRAY['NR-10','NR-12','NR-13'],
 ARRAY['Luva isolante','Óculos de segurança','Capacete classe B','Bota de segurança'])
) AS v(categoria,nome,efeitos_tipicos,medidas_controle_padrao,nrs_aplicaveis,epis_sugeridos)
WHERE NOT EXISTS (
  SELECT 1 FROM public.catalogo_riscos c WHERE lower(c.nome) = lower(v.nome)
);