
ALTER TABLE public.acidentes_trabalho
  ADD COLUMN IF NOT EXISTS vitima_nome_mae text,
  ADD COLUMN IF NOT EXISTS vitima_data_nascimento date,
  ADD COLUMN IF NOT EXISTS vitima_sexo text CHECK (vitima_sexo IN ('M','F') OR vitima_sexo IS NULL),
  ADD COLUMN IF NOT EXISTS vitima_estado_civil text,
  ADD COLUMN IF NOT EXISTS vitima_grau_instrucao text,
  ADD COLUMN IF NOT EXISTS vitima_remuneracao numeric(12,2),
  ADD COLUMN IF NOT EXISTS vitima_ctps text,
  ADD COLUMN IF NOT EXISTS vitima_rg text,
  ADD COLUMN IF NOT EXISTS vitima_pis text,
  ADD COLUMN IF NOT EXISTS vitima_telefone text,
  ADD COLUMN IF NOT EXISTS vitima_cbo text,
  ADD COLUMN IF NOT EXISTS vitima_aposentado boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS vitima_area text CHECK (vitima_area IN ('URBANA','RURAL') OR vitima_area IS NULL),
  ADD COLUMN IF NOT EXISTS vitima_filiacao text,
  ADD COLUMN IF NOT EXISTS horas_trabalhadas_antes numeric(4,2),
  ADD COLUMN IF NOT EXISTS cnpj_prestadora text,
  ADD COLUMN IF NOT EXISTS ultimo_dia_trabalhado date,
  ADD COLUMN IF NOT EXISTS atestado_unidade text,
  ADD COLUMN IF NOT EXISTS atestado_hora text,
  ADD COLUMN IF NOT EXISTS atestado_observacoes text,
  ADD COLUMN IF NOT EXISTS emitente_email text,
  ADD COLUMN IF NOT EXISTS sera_afastado boolean DEFAULT false;
