ALTER TABLE public.audit_logs DROP CONSTRAINT IF EXISTS audit_logs_action_check;
ALTER TABLE public.audit_logs ADD CONSTRAINT audit_logs_action_check CHECK (action = ANY (ARRAY[
 'INSERT','UPDATE','DELETE','READ','LOGIN','LOGOUT',
 'RC_STATUS_CHANGE','RC_DISPENSA_COTACAO','RC_DISPENSA_REVOGADA','RC_DEVOLVIDA_PARA_COTACAO',
 'REATIVAR_FUNCIONARIO','REBAIXAR_ADMIN','PURGE_INVITES','FORCE_SIGNOUT','MFA_ENROLL','MFA_UNENROLL',
 'HARD_DELETE_EMPLOYEE','MUDANCA_CARGO','MUDANCA_GHE',
 'DESLIGAMENTO_EM_BLOCO','HARD_DELETE_COMPANY','DESATIVAR_EMPRESA','REATIVAR_EMPRESA'
]));