INSERT INTO public.apr_modelos (codigo, nome, categoria, descricao_curta, atividade_descricao, setor_padrao, exige_pte, ptes_sugeridas, ordem, riscos) VALUES

('corte-esmerilhamento-patio', 'Corte e esmerilhamento de peças no pátio', 'CORTE_SOLDA',
 'Oficina/pátio descoberto — operação de corte e esmerilhamento de peças metálicas',
 'Corte e esmerilhamento de peças metálicas no pátio do estaleiro, com uso de esmerilhadeira angular, maçarico ou serra. Trabalho a céu aberto, com projeção de fagulhas e partículas.',
 'Pátio / Oficina', true, ARRAY['Trabalho a Quente'], 10,
 '[
  {"risco_nome":"Projeção de partículas e fagulhas","risco_categoria":"ACIDENTE","efeitos_danos":"Lesão ocular, queimadura em pele","probabilidade":3,"severidade":3,"acoes_preventivas":"Uso obrigatório de óculos ampla visão + protetor facial; isolamento da área com biombo; remoção de material combustível em raio de 5m","epis":["Óculos ampla visão","Protetor facial","Luva raspa","Avental raspa","Perneira raspa"],"nrs":["NR-06","NR-12","NR-34"],"passo_a_passo":"Posicionar peça em bancada estável, isolar área, executar corte/esmerilhamento mantendo o corpo fora do plano de projeção"},
  {"risco_nome":"Incêndio por fagulhas em material combustível","risco_categoria":"ACIDENTE","efeitos_danos":"Queimaduras graves, perda patrimonial","probabilidade":2,"severidade":3,"acoes_preventivas":"Extintor PQS 6kg a 5m; vigia de fogo durante e 30min após; remoção de óleos/papéis/madeira da área","epis":["Uniforme de raspa ou algodão tratado"],"nrs":["NR-23","NR-34"],"passo_a_passo":"Vigia de fogo posicionado antes do início; extintor testado e na área"},
  {"risco_nome":"Ruído ocupacional acima de 85dB","risco_categoria":"FISICO","efeitos_danos":"Perda auditiva induzida por ruído (PAIR)","probabilidade":3,"severidade":2,"acoes_preventivas":"Protetor auricular tipo plug + concha (atenuação combinada); rodízio de tarefas","epis":["Protetor auricular plug","Protetor auricular concha"],"nrs":["NR-06","NR-15"]},
  {"risco_nome":"Inalação de fumos metálicos e poeira","risco_categoria":"QUIMICO","efeitos_danos":"Doença respiratória, siderose, intoxicação por manganês","probabilidade":2,"severidade":3,"acoes_preventivas":"Respirador PFF2 com filtro P2; trabalhar a favor do vento; pausas em área ventilada","epis":["Respirador PFF2","Touca árabe"],"nrs":["NR-06","NR-09","NR-15"]},
  {"risco_nome":"Choque elétrico em equipamento energizado","risco_categoria":"ACIDENTE","efeitos_danos":"Choque, parada cardíaca, queimadura elétrica","probabilidade":1,"severidade":3,"acoes_preventivas":"Equipamento aterrado; cabo sem emendas expostas; DR no quadro; inspeção visual antes do uso","epis":["Botina com biqueira composite","Luva isolante"],"nrs":["NR-10","NR-12"]},
  {"risco_nome":"Exposição solar prolongada","risco_categoria":"FISICO","efeitos_danos":"Insolação, desidratação, queimadura UV","probabilidade":3,"severidade":2,"acoes_preventivas":"Cobertura/tenda no posto; pausas a cada 50min; hidratação a cada 30min; FPS 50","epis":["Chapéu árabe","Óculos UV","Camisa manga longa"],"nrs":["NR-21"]}
 ]'::jsonb),

('solda-altura-casco', 'Solda em altura dentro do casco', 'ALTURA',
 'Soldador trabalhando suspenso/em altura dentro das cavidades estruturais internas do casco',
 'Solda elétrica em altura (>2m) dentro das cavidades estruturais internas do casco — costelas, anteparas, longarinas. Espaço parcialmente confinado, com risco simultâneo de altura, queda, queimaduras e exposição a fumos.',
 'Montagem / Estrutura — Casco', true, ARRAY['Trabalho em Altura','Trabalho a Quente'], 20,
 '[
  {"risco_nome":"Queda de altura (>2m)","risco_categoria":"ACIDENTE","efeitos_danos":"Politraumatismo, óbito","probabilidade":3,"severidade":3,"acoes_preventivas":"Cinto paraquedista com talabarte duplo em Y; ancoragem ≥1500kgf em estrutura fixa; linha de vida quando deslocamento horizontal; análise prévia do ponto de ancoragem pelo TST","epis":["Cinto paraquedista","Talabarte duplo Y absorvedor","Capacete jugular"],"nrs":["NR-35","NR-06"],"passo_a_passo":"Inspecionar EPI antes da subida; ancorar SEMPRE antes de soltar a mão da estrutura; nunca desconectar ambos os ganchos simultaneamente"},
  {"risco_nome":"Queda de ferramenta/material sobre pessoas abaixo","risco_categoria":"ACIDENTE","efeitos_danos":"Lesão grave em terceiro, óbito","probabilidade":3,"severidade":3,"acoes_preventivas":"Isolamento total da projeção em solo com cone/fita; placa ÁREA INTERDITADA; ferramentas amarradas com cabo-vida; eletrodos em bolsa fechada","epis":["Capacete jugular para quem está abaixo"],"nrs":["NR-35","NR-18"]},
  {"risco_nome":"Queimadura por respingo de solda","risco_categoria":"ACIDENTE","efeitos_danos":"Queimadura de 2º/3º grau em pele e olhos","probabilidade":3,"severidade":2,"acoes_preventivas":"Vestimenta de raspa íntegra; máscara de solda com lente correta; touca árabe; manter o corpo fora da trajetória do respingo","epis":["Máscara de solda automática","Avental raspa","Mangote raspa","Luva raspa cano longo","Perneira raspa","Touca árabe"],"nrs":["NR-06","NR-34"]},
  {"risco_nome":"Inalação de fumos de solda em ambiente fechado","risco_categoria":"QUIMICO","efeitos_danos":"Febre dos fumos metálicos, doença pulmonar crônica","probabilidade":3,"severidade":3,"acoes_preventivas":"Exaustão localizada obrigatória; respirador PFF2 com filtro para fumos; rodízio com pausa em área ventilada a cada 1h","epis":["Respirador PFF2 para fumos","Touca árabe"],"nrs":["NR-09","NR-15","NR-34"]},
  {"risco_nome":"Choque elétrico do equipamento de solda","risco_categoria":"ACIDENTE","efeitos_danos":"Choque, fibrilação, queda em altura por contração","probabilidade":2,"severidade":3,"acoes_preventivas":"Cabo de solda sem emendas; porta-eletrodo isolado; aterramento da peça; luva isolante; superfície seca","epis":["Luva raspa sobre luva isolante","Botina isolante"],"nrs":["NR-10","NR-12","NR-34"]},
  {"risco_nome":"Incêndio por respingos em material combustível","risco_categoria":"ACIDENTE","efeitos_danos":"Queimaduras, perda patrimonial","probabilidade":2,"severidade":3,"acoes_preventivas":"Vigia de fogo no nível inferior; extintor PQS na área; manta antifagulha sob o ponto de solda; inspeção pós-trabalho por 30min","epis":[],"nrs":["NR-23","NR-34"]}
 ]'::jsonb),

('solda-montagem-estrutura-baixa', 'Solda e montagem em estrutura metálica baixa', 'CORTE_SOLDA',
 'Dois ou mais soldadores em treliça/estrutura baixa (<2m), montagem com solda elétrica',
 'Solda elétrica e montagem em estrutura metálica abaixo de 2m de altura — treliças, bases, suportes. Múltiplos soldadores trabalhando próximos.',
 'Montagem / Estrutura', true, ARRAY['Trabalho a Quente'], 30,
 '[
  {"risco_nome":"Queimadura por respingo de solda","risco_categoria":"ACIDENTE","efeitos_danos":"Queimadura em pele e olhos","probabilidade":3,"severidade":2,"acoes_preventivas":"Vestimenta de raspa íntegra; máscara de solda com lente apropriada; biombo entre soldadores próximos para não cegar terceiros","epis":["Máscara de solda automática","Avental raspa","Mangote raspa","Luva raspa cano longo","Perneira raspa"],"nrs":["NR-06","NR-34"]},
  {"risco_nome":"Radiação não-ionizante (arco voltaico) sobre terceiros","risco_categoria":"FISICO","efeitos_danos":"Queimadura de córnea (olho de solda), queimadura de pele","probabilidade":3,"severidade":2,"acoes_preventivas":"Biombo de solda entre estações; sinalização ATENÇÃO ARCO VOLTAICO; terceiros próximos com óculos escuros tonalidade 5","epis":["Óculos escuros tonalidade 5 (auxiliar)","Máscara solda (operador)"],"nrs":["NR-06","NR-34"]},
  {"risco_nome":"Inalação de fumos metálicos","risco_categoria":"QUIMICO","efeitos_danos":"Doença respiratória","probabilidade":2,"severidade":3,"acoes_preventivas":"Trabalhar a favor do vento; respirador PFF2; pausas em área ventilada","epis":["Respirador PFF2 para fumos"],"nrs":["NR-09","NR-15","NR-34"]},
  {"risco_nome":"Choque elétrico do equipamento de solda","risco_categoria":"ACIDENTE","efeitos_danos":"Choque, fibrilação","probabilidade":2,"severidade":3,"acoes_preventivas":"Aterramento da peça; cabo íntegro; porta-eletrodo isolado; superfície seca","epis":["Botina isolante","Luva raspa"],"nrs":["NR-10","NR-12"]},
  {"risco_nome":"Postura inadequada (agachado/ajoelhado por tempo prolongado)","risco_categoria":"ERGONOMICO","efeitos_danos":"LER/DORT em joelhos, coluna lombar","probabilidade":3,"severidade":2,"acoes_preventivas":"Joelheira; pausas de 10min a cada 50min; alternar postura; bancada quando possível","epis":["Joelheira"],"nrs":["NR-17"]},
  {"risco_nome":"Incêndio por respingos","risco_categoria":"ACIDENTE","efeitos_danos":"Queimaduras, perda patrimonial","probabilidade":2,"severidade":2,"acoes_preventivas":"Extintor PQS na área; remoção de combustíveis em 5m; vigia de fogo 30min pós-trabalho","epis":[],"nrs":["NR-23","NR-34"]}
 ]'::jsonb),

('jateamento-altura-costado', 'Jateamento em altura no costado', 'JATEAMENTO',
 'Jatista trabalhando no topo do costado (>2m) com mangueira de jato abrasivo',
 'Jateamento abrasivo em altura no costado do casco, com mangueira pressurizada e granalha. Trabalhador no topo do costado (>2m), exposto a abrasivos, ruído, poeira e risco de queda.',
 'Pintura / Jateamento — Costado', true, ARRAY['Trabalho em Altura'], 40,
 '[
  {"risco_nome":"Queda de altura (>2m)","risco_categoria":"ACIDENTE","efeitos_danos":"Politraumatismo, óbito","probabilidade":3,"severidade":3,"acoes_preventivas":"Cinto paraquedista com talabarte duplo Y; linha de vida horizontal ancorada ≥1500kgf; análise do ponto de ancoragem pelo TST ANTES do início","epis":["Cinto paraquedista","Talabarte duplo Y absorvedor","Capacete jugular"],"nrs":["NR-35","NR-06"],"passo_a_passo":"Instalar linha de vida ANTES da primeira subida; manter pelo menos um talabarte ancorado a todo momento; o reacão do jato pode desestabilizar — ancorar com cabo curto"},
  {"risco_nome":"Reação do jato pressurizado (chicote da mangueira)","risco_categoria":"ACIDENTE","efeitos_danos":"Queda por desequilíbrio, lesão por impacto da mangueira","probabilidade":3,"severidade":3,"acoes_preventivas":"Válvula de segurança deadman no bico; mangueira fixada à estrutura; talabarte curto para impedir queda; operador treinado","epis":["Capacete jugular","Cinto paraquedista"],"nrs":["NR-35","NR-12"]},
  {"risco_nome":"Inalação de poeira/abrasivo e tinta antiga","risco_categoria":"QUIMICO","efeitos_danos":"Silicose, intoxicação por chumbo/zinco da tinta","probabilidade":3,"severidade":3,"acoes_preventivas":"Capuz de jateamento com ar mandado (linha de ar respirável); compressor com filtro de óleo; análise do ar respirável","epis":["Capuz de jateamento com ar mandado","Macacão de jateamento","Luva longa","Bota borracha"],"nrs":["NR-06","NR-09","NR-15"]},
  {"risco_nome":"Ruído extremo (>110dB)","risco_categoria":"FISICO","efeitos_danos":"PAIR aguda, ruptura de tímpano","probabilidade":3,"severidade":3,"acoes_preventivas":"Protetor auricular plug + concha (atenuação combinada); capuz com proteção acústica","epis":["Protetor auricular plug","Protetor auricular concha"],"nrs":["NR-06","NR-15"]},
  {"risco_nome":"Queda de objetos/abrasivo sobre pessoas abaixo","risco_categoria":"ACIDENTE","efeitos_danos":"Lesão em terceiros, contaminação","probabilidade":3,"severidade":2,"acoes_preventivas":"Isolamento total da projeção em solo; placa ÁREA INTERDITADA; lona de contenção quando possível; ninguém abaixo durante o jato","epis":[],"nrs":["NR-35","NR-18"]},
  {"risco_nome":"Vibração da mangueira (mão-braço)","risco_categoria":"FISICO","efeitos_danos":"Síndrome vibração mão-braço, perda tátil","probabilidade":2,"severidade":2,"acoes_preventivas":"Rodízio de operadores a cada 1h; luva anti-vibração; pausa de 10min a cada 50min","epis":["Luva anti-vibração"],"nrs":["NR-09","NR-15","NR-17"]}
 ]'::jsonb),

('icamento-longarina', 'Içamento de longarina com pau-de-carga', 'ICAMENTO',
 'Operação de içamento de longarina/peça estrutural longa com guindaste ou pau-de-carga',
 'Içamento e posicionamento de longarina (~XXX kg) com pau-de-carga / guindaste — incluindo sinaleiro, operador, montadores no topo recebendo a peça.',
 'Montagem / Estrutura — Casco', true, ARRAY['Trabalho em Altura','Içamento de Carga'], 50,
 '[
  {"risco_nome":"Queda da carga durante o içamento","risco_categoria":"ACIDENTE","efeitos_danos":"Esmagamento, óbito","probabilidade":2,"severidade":3,"acoes_preventivas":"Estropos com CMT ≥ 2× peso da carga; inspeção visual antes do içamento; ângulo do estropo ≤60°; teste de pré-içamento a 30cm do solo","epis":["Capacete jugular","Luva raspa"],"nrs":["NR-11","NR-12"],"passo_a_passo":"Sinaleiro único; rádio HT em frequência exclusiva; rota de içamento livre; içamento a 30cm e parada para verificar centro de gravidade"},
  {"risco_nome":"Queda de pessoa abaixo da projeção da carga","risco_categoria":"ACIDENTE","efeitos_danos":"Esmagamento, óbito","probabilidade":3,"severidade":3,"acoes_preventivas":"Isolamento total da projeção com cone/fita; placa ÁREA DE IÇAMENTO — NÃO CIRCULAR; sinaleiro mantém visual da rota","epis":["Capacete jugular"],"nrs":["NR-11","NR-35"]},
  {"risco_nome":"Queda de altura de quem recebe a peça","risco_categoria":"ACIDENTE","efeitos_danos":"Politraumatismo, óbito","probabilidade":3,"severidade":3,"acoes_preventivas":"Montadores ancorados com talabarte duplo Y; linha de vida quando deslocamento; ancoragem ≥1500kgf testada","epis":["Cinto paraquedista","Talabarte duplo Y","Capacete jugular"],"nrs":["NR-35"]},
  {"risco_nome":"Falha do equipamento de içamento","risco_categoria":"MECANICO","efeitos_danos":"Queda da carga","probabilidade":1,"severidade":3,"acoes_preventivas":"Checklist do equipamento assinado; inspeção mensal dos estropos; ART do plano de rigging","epis":[],"nrs":["NR-11","NR-12"]},
  {"risco_nome":"Comunicação falha entre sinaleiro e operador","risco_categoria":"ACIDENTE","efeitos_danos":"Movimento inesperado da carga","probabilidade":2,"severidade":3,"acoes_preventivas":"Sinaleiro único e identificado; rádio HT exclusivo; gestos padrão ABNT; pré-briefing antes do içamento","epis":["Colete refletivo (sinaleiro)"],"nrs":["NR-11"]}
 ]'::jsonb),

('icamento-contrapesos-concreto', 'Içamento de contrapesos de concreto', 'ICAMENTO',
 'Içamento e posicionamento de blocos de contrapeso de concreto no topo do casco',
 'Içamento e posicionamento de contrapesos de concreto (~XXX kg cada) com pau-de-carga, descarregando no topo do casco / costado. Montadores recebem a peça em altura.',
 'Montagem / Estrutura — Casco', true, ARRAY['Trabalho em Altura','Içamento de Carga'], 60,
 '[
  {"risco_nome":"Queda do contrapeso sobre pessoa","risco_categoria":"ACIDENTE","efeitos_danos":"Esmagamento, óbito","probabilidade":3,"severidade":3,"acoes_preventivas":"Estropos com CMT ≥ 2× peso; cabo de retenção; isolamento total da projeção; nenhuma pessoa sob carga; teste pré-içamento a 30cm","epis":["Capacete jugular"],"nrs":["NR-11","NR-12"],"passo_a_passo":"Verificar olhal/içamento do contrapeso ANTES de conectar; sinaleiro único; içamento lento; rotação controlada com cabo guia"},
  {"risco_nome":"Queda de altura de quem recebe a peça","risco_categoria":"ACIDENTE","efeitos_danos":"Politraumatismo, óbito","probabilidade":3,"severidade":3,"acoes_preventivas":"Cinto paraquedista com talabarte duplo Y ancorado em ponto ≥1500kgf; linha de vida horizontal no topo do casco","epis":["Cinto paraquedista","Talabarte duplo Y","Capacete jugular"],"nrs":["NR-35"]},
  {"risco_nome":"Falha do olhal/ponto de içamento da peça","risco_categoria":"MECANICO","efeitos_danos":"Queda da carga","probabilidade":2,"severidade":3,"acoes_preventivas":"Inspeção do olhal antes de cada içamento; teste de carga; descarte se houver trinca","epis":[],"nrs":["NR-11","NR-12"]},
  {"risco_nome":"Esmagamento de mão no posicionamento da peça","risco_categoria":"ACIDENTE","efeitos_danos":"Fratura, amputação","probabilidade":2,"severidade":3,"acoes_preventivas":"Cabo guia para posicionar a peça SEM colocar a mão; comando MÃOS LIVRES até a peça pousar; posicionamento com peça parada","epis":["Luva raspa"],"nrs":["NR-11","NR-12"]},
  {"risco_nome":"Exposição solar prolongada no topo do casco","risco_categoria":"FISICO","efeitos_danos":"Insolação, desidratação","probabilidade":3,"severidade":2,"acoes_preventivas":"Hidratação a cada 30min; pausa à sombra; FPS 50; chapéu árabe sob o capacete","epis":["Chapéu árabe","Óculos UV"],"nrs":["NR-21"]}
 ]'::jsonb),

('corte-solda-costado-oxicorte', 'Corte e solda no costado com oxicorte (O₂)', 'CORTE_SOLDA',
 'Corte/solda em costado usando maçarico com cilindros de oxigênio e GLP/acetileno',
 'Corte e solda no costado do casco com oxicorte (maçarico com cilindros pressurizados de oxigênio e GLP/acetileno). Inclui trabalho a quente, possivelmente em altura.',
 'Pré-fabricação / Casco', true, ARRAY['Trabalho a Quente','Trabalho em Altura'], 70,
 '[
  {"risco_nome":"Explosão dos cilindros de O₂/GLP/acetileno","risco_categoria":"ACIDENTE","efeitos_danos":"Óbito, destruição patrimonial","probabilidade":1,"severidade":3,"acoes_preventivas":"Cilindros em pé, amarrados, com capacete protetor; válvula de retrocesso de chama em AMBOS gases; mangueiras inspecionadas; manter a 5m de fonte de calor","epis":[],"nrs":["NR-13","NR-34"],"passo_a_passo":"Teste de vazamento com água e sabão antes de acender; nunca usar óleo/graxa em conexão de O₂; fechar cilindros ao final"},
  {"risco_nome":"Queimadura por chama/escória","risco_categoria":"ACIDENTE","efeitos_danos":"Queimadura de 2º/3º grau","probabilidade":3,"severidade":3,"acoes_preventivas":"Vestimenta de raspa íntegra; máscara de oxicorte com lente apropriada; touca árabe; isqueiro de centelha (nunca fósforo)","epis":["Máscara de oxicorte","Avental raspa","Mangote raspa","Luva raspa cano longo","Perneira raspa","Touca árabe"],"nrs":["NR-06","NR-34"]},
  {"risco_nome":"Inalação de fumos e gases (NOx, CO)","risco_categoria":"QUIMICO","efeitos_danos":"Intoxicação aguda, doença respiratória","probabilidade":3,"severidade":3,"acoes_preventivas":"Trabalhar a favor do vento; ventilação forçada em ambiente fechado; respirador PFF2 com filtro para gases ácidos","epis":["Respirador PFF2"],"nrs":["NR-09","NR-15","NR-34"]},
  {"risco_nome":"Incêndio por escória em material combustível","risco_categoria":"ACIDENTE","efeitos_danos":"Queimaduras, perda patrimonial","probabilidade":3,"severidade":3,"acoes_preventivas":"Vigia de fogo durante e 30min após; extintor PQS na área; remoção de combustíveis em 10m; manta antifagulha","epis":[],"nrs":["NR-23","NR-34"]},
  {"risco_nome":"Retrocesso de chama dentro da mangueira","risco_categoria":"ACIDENTE","efeitos_danos":"Explosão da mangueira","probabilidade":1,"severidade":3,"acoes_preventivas":"Válvula anti-retrocesso na saída do maçarico E no cilindro; mangueiras com cores ABNT; inspeção visual","epis":[],"nrs":["NR-13","NR-34"]}
 ]'::jsonb),

('trabalho-quente-cesto-aereo', 'Trabalho a quente em cesto aéreo', 'CESTO_AEREO',
 'Solda/corte executado dentro de cesto aéreo (plataforma elevatória), em altura',
 'Solda ou corte executado dentro de cesto aéreo (PEMT) com operador dentro da cesta, em altura. Combina riscos de içamento de pessoas, altura e trabalho a quente.',
 'Montagem / Estrutura', true, ARRAY['Trabalho em Altura','Trabalho a Quente','Içamento de Carga'], 80,
 '[
  {"risco_nome":"Queda do cesto aéreo","risco_categoria":"ACIDENTE","efeitos_danos":"Óbito","probabilidade":2,"severidade":3,"acoes_preventivas":"Plano de rigging assinado por engenheiro mecânico com ART; checklist do equipamento; operador capacitado NR-11/NR-18; cinto paraquedista ancorado DENTRO do cesto","epis":["Cinto paraquedista","Talabarte de retenção curto","Capacete jugular"],"nrs":["NR-11","NR-12","NR-35"],"passo_a_passo":"Inspeção do equipamento + checklist assinado; teste de funcionamento sem carga; subida lenta com sinaleiro no solo"},
  {"risco_nome":"Queda do operador para fora do cesto","risco_categoria":"ACIDENTE","efeitos_danos":"Politraumatismo, óbito","probabilidade":2,"severidade":3,"acoes_preventivas":"Cinto paraquedista ancorado a ponto FIXO da cesta; não escalar guarda-corpo; não inclinar para fora","epis":["Cinto paraquedista","Talabarte curto"],"nrs":["NR-35"]},
  {"risco_nome":"Queimadura por respingo de solda","risco_categoria":"ACIDENTE","efeitos_danos":"Queimadura em pele/olhos","probabilidade":3,"severidade":2,"acoes_preventivas":"Vestimenta de raspa íntegra; máscara de solda; manta antifagulha no piso do cesto","epis":["Máscara de solda","Avental raspa","Mangote raspa","Luva raspa cano longo"],"nrs":["NR-06","NR-34"]},
  {"risco_nome":"Incêndio dentro do cesto","risco_categoria":"ACIDENTE","efeitos_danos":"Queimaduras graves, queda","probabilidade":2,"severidade":3,"acoes_preventivas":"Extintor dentro do cesto; vigia de fogo no solo; remoção de combustíveis na projeção","epis":[],"nrs":["NR-23","NR-34"]},
  {"risco_nome":"Movimento inesperado do cesto","risco_categoria":"ACIDENTE","efeitos_danos":"Lesão por colisão, queda","probabilidade":2,"severidade":3,"acoes_preventivas":"Operador no solo treinado; sinaleiro único; rádio HT; não operar com vento >40km/h","epis":[],"nrs":["NR-11","NR-12"]}
 ]'::jsonb),

('solda-overhead-andaime', 'Solda overhead em andaime', 'CORTE_SOLDA',
 'Solda no teto/face superior (overhead) executada de cima de andaime acima de 2m',
 'Solda em posição overhead (no teto / face superior da peça) executada de cima de andaime acima de 2m. Pior posição para respingo — risco de cair direto no rosto/corpo do soldador.',
 'Montagem / Estrutura', true, ARRAY['Trabalho em Altura','Trabalho a Quente'], 90,
 '[
  {"risco_nome":"Queimadura por respingo direto no rosto/pescoço","risco_categoria":"ACIDENTE","efeitos_danos":"Queimadura de 3º grau em face, perda visual","probabilidade":3,"severidade":3,"acoes_preventivas":"Máscara de solda com proteção facial completa; touca árabe cobrindo pescoço; jaqueta de raspa abotoada até o pescoço; manga de raspa sobre o braço","epis":["Máscara de solda automática completa","Touca árabe","Jaqueta raspa","Mangote raspa","Luva raspa cano longo"],"nrs":["NR-06","NR-34"],"passo_a_passo":"Posicionar-se de modo que o respingo NÃO caia perpendicular sobre o corpo; usar bandagem de proteção no pescoço"},
  {"risco_nome":"Queda de altura do andaime (>2m)","risco_categoria":"ACIDENTE","efeitos_danos":"Politraumatismo, óbito","probabilidade":3,"severidade":3,"acoes_preventivas":"Andaime montado por profissional NR-18; guarda-corpo + rodapé; cinto paraquedista ancorado em ponto FIXO (não no andaime)","epis":["Cinto paraquedista","Talabarte duplo Y","Capacete jugular"],"nrs":["NR-35","NR-18"]},
  {"risco_nome":"Inalação de fumos (concentrados pela posição overhead)","risco_categoria":"QUIMICO","efeitos_danos":"Febre dos fumos, doença respiratória","probabilidade":3,"severidade":3,"acoes_preventivas":"Respirador PFF2 com filtro para fumos OBRIGATÓRIO (overhead concentra fumos); exaustão localizada; pausas frequentes","epis":["Respirador PFF2 para fumos","Touca árabe"],"nrs":["NR-09","NR-15","NR-34"]},
  {"risco_nome":"Postura cervical forçada (olhar para cima por tempo prolongado)","risco_categoria":"ERGONOMICO","efeitos_danos":"Cervicalgia crônica, LER","probabilidade":3,"severidade":2,"acoes_preventivas":"Rodízio de soldadores a cada 1h; alongamento cervical antes e depois; pausa de 10min a cada 50min","epis":[],"nrs":["NR-17"]},
  {"risco_nome":"Incêndio por respingos caindo em material combustível","risco_categoria":"ACIDENTE","efeitos_danos":"Queimaduras, perda patrimonial","probabilidade":3,"severidade":3,"acoes_preventivas":"Manta antifagulha sob o ponto de solda; vigia de fogo no nível inferior; extintor PQS na área; inspeção pós-trabalho 30min","epis":[],"nrs":["NR-23","NR-34"]}
 ]'::jsonb);