CREATE TABLE IF NOT EXISTS public.apr_acoes_biblioteca (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  categoria text NOT NULL,
  risco_padrao text NOT NULL,
  palavras_chave text[] NOT NULL DEFAULT '{}',
  catalogo_risco_id uuid REFERENCES public.catalogo_riscos(id) ON DELETE SET NULL,
  hierarquia text NOT NULL DEFAULT 'ADMINISTRATIVA',
  acao text NOT NULL,
  como text,
  efeitos_danos text,
  epis text[] NOT NULL DEFAULT '{}',
  nrs text[] NOT NULL DEFAULT '{}',
  prioridade text NOT NULL DEFAULT 'MEDIA',
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.apr_acoes_biblioteca TO authenticated;
GRANT ALL ON public.apr_acoes_biblioteca TO service_role;

ALTER TABLE public.apr_acoes_biblioteca ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Acoes APR: leitura autenticada" ON public.apr_acoes_biblioteca
  FOR SELECT TO authenticated USING (is_viewer_or_above(auth.uid()));
CREATE POLICY "Acoes APR: editores podem inserir" ON public.apr_acoes_biblioteca
  FOR INSERT TO authenticated WITH CHECK (is_editor(auth.uid()));
CREATE POLICY "Acoes APR: editores podem atualizar" ON public.apr_acoes_biblioteca
  FOR UPDATE TO authenticated USING (is_editor(auth.uid()));
CREATE POLICY "Acoes APR: admin pode excluir" ON public.apr_acoes_biblioteca
  FOR DELETE TO authenticated USING (has_role(auth.uid(), 'admin'::app_role));

CREATE OR REPLACE FUNCTION public.apr_acoes_biblioteca_touch()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END; $$;

DROP TRIGGER IF EXISTS trg_apr_acoes_biblioteca_touch ON public.apr_acoes_biblioteca;
CREATE TRIGGER trg_apr_acoes_biblioteca_touch BEFORE UPDATE ON public.apr_acoes_biblioteca
FOR EACH ROW EXECUTE FUNCTION public.apr_acoes_biblioteca_touch();

CREATE INDEX IF NOT EXISTS idx_apr_acoes_kw ON public.apr_acoes_biblioteca USING gin (palavras_chave);

INSERT INTO public.apr_acoes_biblioteca (categoria, risco_padrao, palavras_chave, hierarquia, acao, como, efeitos_danos, epis, nrs, prioridade) VALUES
('ACIDENTE','Içamento de carga',ARRAY['icamento','iça','guindaste','carga suspensa','munck','talha'],'ENGENHARIA','Utilizar acessórios de içamento certificados e inspecionados','Cintas, manilhas e garras com certificado e inspeção pré-uso registrada; descartar item com dano','Queda de carga, esmagamento, óbito',ARRAY['Capacete jugular','Botina biqueira composite','Luva vaqueta'],ARRAY['NR-11','NR-12','NR-34'],'ALTA'),
('ACIDENTE','Içamento de carga',ARRAY['icamento','carga suspensa','guindaste'],'ADMINISTRATIVA','Isolar o raio de ação e proibir permanência sob carga suspensa','Cones e fita zebrada em todo o raio; sinaleiro exclusivo com rádio; ninguém sob a carga','Esmagamento, óbito',ARRAY['Colete refletivo'],ARRAY['NR-11','NR-34'],'ALTA'),
('ACIDENTE','Içamento de carga',ARRAY['icamento','plano de rigging','carga'],'ADMINISTRATIVA','Elaborar plano de rigging e conferir peso x capacidade','Definir CG, ângulo de cintas, tabela de carga do equipamento e checagem do operador habilitado','Tombamento do equipamento, queda de carga',ARRAY[]::text[],ARRAY['NR-11','NR-12'],'ALTA'),
('ACIDENTE','Movimentação e assentamento de chapa',ARRAY['chapa','garra','berco','assentamento'],'ENGENHARIA','Usar berço/cavalete estável para assentamento da chapa','Berço nivelado, calços e travas laterais antes de soltar a garra','Prensagem de mãos e pés, tombamento',ARRAY['Luva anticorte nível 5','Botina biqueira composite'],ARRAY['NR-11','NR-34'],'ALTA'),
('ACIDENTE','Prensagem de mãos e pés',ARRAY['prensagem','esmagamento','chapa','peca'],'ADMINISTRATIVA','Guiar cargas somente com cabo-guia, nunca com as mãos','Cabo-guia de no mínimo 2 m; mãos fora da linha de fogo em todo o assentamento','Amputação, fratura, contusão',ARRAY['Luva anticorte nível 5'],ARRAY['NR-11','NR-12'],'ALTA'),
('ACIDENTE','Corte por chapa/rebarba',ARRAY['corte','rebarba','chapa','borda'],'EPI','Manuseio com luva anticorte e rebarbação prévia das bordas','Rebarbar bordas cortantes antes do manuseio; luva anticorte nível 5','Corte profundo, laceração',ARRAY['Luva anticorte nível 5','Manguito'],ARRAY['NR-06','NR-12'],'MEDIA'),
('ACIDENTE','Trabalho em altura',ARRAY['altura','andaime','cesto','escada','queda'],'ENGENHARIA','Instalar linha de vida e guarda-corpo antes do acesso','Linha de vida dimensionada por profissional legalmente habilitado; guarda-corpo com rodapé','Queda de altura, óbito',ARRAY['Cinturão paraquedista','Talabarte duplo com ABS','Capacete jugular'],ARRAY['NR-35','NR-34'],'ALTA'),
('ACIDENTE','Trabalho em altura',ARRAY['altura','permissao','pt','trabalho em altura'],'ADMINISTRATIVA','Emitir Permissão de Trabalho em Altura e checar APF','Análise de risco, PT assinada, trabalhador com NR-35 válida e ASO apto para altura','Queda, óbito',ARRAY['Cinturão paraquedista'],ARRAY['NR-35'],'ALTA'),
('ACIDENTE','Queda de objetos',ARRAY['queda de objeto','ferramenta','altura'],'ENGENHARIA','Amarrar ferramentas e instalar bandeja/tela de proteção','Cordão de ferramenta em 100% dos itens; tela de contenção sob a frente de serviço','TCE, contusão, óbito',ARRAY['Capacete jugular'],ARRAY['NR-34','NR-35'],'ALTA'),
('ACIDENTE','Uso de escada portátil',ARRAY['escada','portatil','apoio'],'ADMINISTRATIVA','Fixar e amarrar a escada em base firme e nivelada','Sapatas antiderrapantes, amarração no topo, ângulo 75°, 1 m acima do ponto de apoio, base sobre piso firme (nunca areia solta)','Queda de mesmo nível e de altura, fratura',ARRAY['Cinturão paraquedista','Capacete jugular'],ARRAY['NR-35','NR-18'],'ALTA'),
('ACIDENTE','Injeção de água em alta pressão',ARRAY['hidrojato','hidrojateamento','alta pressao','jato'],'ENGENHARIA','Usar pistola com gatilho de segurança tipo dead-man','Gatilho de acionamento involuntário travado; mangueira com capa antichicote e teste hidrostático em dia','Injeção dérmica, amputação, infecção grave',ARRAY['Macacão impermeável','Luva de segurança para hidrojato','Protetor facial','Perneira'],ARRAY['NR-06','NR-12','NR-34'],'ALTA'),
('ACIDENTE','Coice/reação da pistola de hidrojato',ARRAY['hidrojato','coice','reacao','pistola'],'ADMINISTRATIVA','Operar em posição firme, com dois apoios e nunca sobre escada instável','Operador com base estável, jato sempre à frente e nunca em direção a pessoas; segundo homem no comando de parada','Perda de equilíbrio, queda, lesão',ARRAY['Cinturão paraquedista'],ARRAY['NR-35','NR-12'],'ALTA'),
('ACIDENTE','Atropelamento por equipamento móvel',ARRAY['atropelamento','empilhadeira','patio','maquina','manobra'],'ENGENHARIA','Segregar rotas de pedestres e de máquinas','Faixas demarcadas, barreiras físicas e travessias sinalizadas no pátio','Atropelamento, óbito',ARRAY['Colete refletivo'],ARRAY['NR-11','NR-12'],'ALTA'),
('ACIDENTE','Ponto cego em manobra',ARRAY['ponto cego','manobra','re','maquina'],'ADMINISTRATIVA','Manobra assistida por sinaleiro e alarme de ré','Sinaleiro treinado e visível, alarme sonoro de ré e giroflex operantes; velocidade máxima 10 km/h','Atropelamento, colisão',ARRAY['Colete refletivo','Capacete'],ARRAY['NR-11','NR-12'],'ALTA'),
('ACIDENTE','Operação de equipamento móvel por não habilitado',ARRAY['operador','habilitacao','maquina','empilhadeira'],'ADMINISTRATIVA','Liberar operação apenas para operador habilitado e autorizado','Conferir treinamento NR-11/NR-12, ASO válido e autorização formal antes do turno','Colisão, tombamento, atropelamento',ARRAY[]::text[],ARRAY['NR-11','NR-12'],'ALTA'),
('ACIDENTE','Tombamento de equipamento',ARRAY['tombamento','patolamento','guindaste','terreno'],'ENGENHARIA','Patolar sobre sapatas e terreno com capacidade de suporte','Sapatas de distribuição, terreno compactado, nivelamento conferido antes do içamento','Tombamento, esmagamento, óbito',ARRAY[]::text[],ARRAY['NR-11','NR-12'],'ALTA'),
('ACIDENTE','Projeção de partículas e fagulhas',ARRAY['projecao','particula','fagulha','esmerilhadeira','corte'],'EPI','Proteção facial completa e biombo de contenção','Óculos ampla visão sob protetor facial; biombo/manta ignífuga contendo a projeção','Lesão ocular, queimadura',ARRAY['Óculos ampla visão','Protetor facial','Avental raspa','Luva raspa'],ARRAY['NR-06','NR-12','NR-34'],'ALTA'),
('ACIDENTE','Incêndio por trabalho a quente',ARRAY['incendio','trabalho a quente','solda','fagulha','oxicorte'],'ADMINISTRATIVA','Vigia de fogo e extintor durante e 30 min após a atividade','Remover combustíveis num raio de 11 m ou proteger com manta; extintor PQS 6 kg a 5 m; PT de trabalho a quente','Queimaduras graves, incêndio, perda patrimonial',ARRAY['Uniforme de raspa'],ARRAY['NR-23','NR-34'],'ALTA'),
('ACIDENTE','Explosão em espaço confinado',ARRAY['confinado','explosao','atmosfera','gas'],'ENGENHARIA','Medir atmosfera e ventilar antes e durante o acesso','Medição de O2, LEL, H2S e CO com equipamento calibrado; ventilação forçada e monitoramento contínuo','Explosão, asfixia, óbito',ARRAY['Detector de 4 gases','Máscara autônoma quando aplicável'],ARRAY['NR-33','NR-34'],'ALTA'),
('ACIDENTE','Choque elétrico',ARRAY['eletrico','choque','energizado','cabo','quadro'],'ENGENHARIA','Alimentar por quadro com DR e aterramento verificado','DR de 30 mA, cabos sem emenda exposta, aterramento testado, inspeção visual antes do uso','Choque, parada cardíaca, queimadura elétrica',ARRAY['Luva isolante','Botina biqueira composite'],ARRAY['NR-10','NR-12'],'ALTA'),
('ACIDENTE','Energia residual / partida acidental',ARRAY['loto','bloqueio','energia','partida','desligamento'],'ENGENHARIA','Aplicar bloqueio e etiquetagem (LOTO) antes da intervenção','Cadeado e etiqueta individual por executante; teste de energia zero antes de iniciar','Choque, esmagamento, amputação',ARRAY[]::text[],ARRAY['NR-10','NR-12'],'ALTA'),
('FISICO','Ruído ocupacional',ARRAY['ruido','db','esmerilhadeira','martelete'],'EPI','Dupla proteção auditiva e rodízio de exposição','Plug + concha em atividades acima de 100 dB; limitar tempo de exposição e afastar terceiros','PAIR, zumbido, estresse',ARRAY['Protetor auricular plug','Protetor auricular concha'],ARRAY['NR-06','NR-15'],'MEDIA'),
('FISICO','Vibração de mãos e braços',ARRAY['vibracao','martelete','esmerilhadeira'],'ADMINISTRATIVA','Rodízio de função e pausas programadas','Máximo de 50 min contínuos com ferramenta vibratória; luva antivibratória e manutenção do equipamento','Síndrome do dedo branco, lesão osteomuscular',ARRAY['Luva antivibratória'],ARRAY['NR-06','NR-15','NR-17'],'MEDIA'),
('FISICO','Calor / sobrecarga térmica',ARRAY['calor','ibutg','termica','sol','ceu aberto'],'ADMINISTRATIVA','Regime de trabalho-descanso e hidratação','Pausa de 10 min a cada 50 min em área sombreada e ventilada; água fresca a até 30 m do posto; monitorar IBUTG','Exaustão térmica, cãibras, intermação',ARRAY['Chapéu árabe','Camisa manga longa'],ARRAY['NR-15','NR-21'],'ALTA'),
('FISICO','Exposição solar / radiação UV',ARRAY['sol','uv','ceu aberto','insolacao'],'ENGENHARIA','Instalar cobertura/tenda sobre o posto de trabalho','Tenda ou lona sobre a frente de serviço; protetor solar FPS 50 reaplicado a cada 3 h','Queimadura, câncer de pele, insolação',ARRAY['Chapéu árabe','Óculos UV','Protetor solar FPS 50'],ARRAY['NR-21'],'MEDIA'),
('FISICO','Chuva e piso escorregadio',ARRAY['chuva','piso','escorregadio','umidade'],'ADMINISTRATIVA','Paralisar atividade crítica em chuva e sinalizar piso molhado','Interromper içamento, altura e trabalho elétrico sob chuva; drenar e sinalizar poças','Queda de mesmo nível, choque, fratura',ARRAY['Capa de chuva','Botina antiderrapante'],ARRAY['NR-18','NR-35'],'MEDIA'),
('FISICO','Descarga atmosférica',ARRAY['raio','descarga atmosferica','tempestade','trovoada'],'ADMINISTRATIVA','Suspender trabalhos externos ao sinal de tempestade','Monitorar alerta meteorológico; ao ouvir trovão, evacuar altura/pátio e aguardar 30 min após o último raio','Eletrocussão, óbito',ARRAY[]::text[],ARRAY['NR-01','NR-35'],'ALTA'),
('FISICO','Radiação não ionizante da solda',ARRAY['solda','uv','radiacao','arco'],'EPI','Máscara de solda com filtro adequado e biombo','Máscara automática com tonalidade correta; biombos protegendo terceiros do arco','Ceratoconjuntivite (mal do arco), queimadura',ARRAY['Máscara de solda automática','Touca de raspa','Avental raspa'],ARRAY['NR-06','NR-34'],'MEDIA'),
('QUIMICO','Fumos metálicos de solda',ARRAY['fumos','solda','metalico','manganes'],'ENGENHARIA','Exaustão localizada ou ventilação forçada na frente de solda','Exaustor com captação junto ao arco; em confinado, insuflação/exaustão contínua','Febre dos fumos metálicos, manganismo, siderose',ARRAY['Respirador PFF2','Respirador semifacial com filtro combinado'],ARRAY['NR-09','NR-15','NR-33'],'ALTA'),
('QUIMICO','Poeira/névoa de jateamento e hidrojato',ARRAY['jateamento','hidrojato','nevoa','poeira','tinta'],'EPI','Proteção respiratória e corporal adequada ao agente','Respirador conforme FISPQ do revestimento removido; macacão impermeável e protetor facial','Doença respiratória, dermatose, intoxicação',ARRAY['Respirador PFF2','Macacão impermeável','Protetor facial'],ARRAY['NR-06','NR-09','NR-15'],'ALTA'),
('QUIMICO','Contato com produto químico',ARRAY['quimico','solvente','tinta','fispq'],'ADMINISTRATIVA','Disponibilizar FISPQ e treinar manuseio antes do uso','FISPQ no local, rotulagem GHS, EPI conforme ficha, kit de emergência e lava-olhos acessível','Dermatose, queimadura química, intoxicação',ARRAY['Luva nitrílica','Óculos ampla visão','Avental químico'],ARRAY['NR-06','NR-09','NR-26'],'MEDIA'),
('ERGONOMICO','Postura forçada e esforço excessivo',ARRAY['postura','esforco','levantamento','ergonomia','overhead'],'ADMINISTRATIVA','Uso de dispositivo de auxílio e revezamento postural','Talha/carrinho para cargas acima de 20 kg; revezamento a cada 30 min em posição overhead ou agachada','Lombalgia, LER/DORT, tendinite',ARRAY[]::text[],ARRAY['NR-17'],'MEDIA'),
('ACIDENTE','Atividades simultâneas incompatíveis',ARRAY['simultanea','simultaneas','sobreposicao','interferencia','icamento e solda'],'ADMINISTRATIVA','Compatibilizar tarefas no planejamento diário e proibir sobreposição','Matriz de compatibilidade na reunião de planejamento; içamento sobre frente de trabalho a quente é proibido; parar uma das frentes','Queda de carga sobre pessoas, incêndio, óbito',ARRAY[]::text[],ARRAY['NR-01','NR-11','NR-34'],'ALTA'),
('ACIDENTE','Atividades simultâneas incompatíveis',ARRAY['simultanea','isolamento','area','frente de servico'],'ENGENHARIA','Isolar verticalmente as frentes sobrepostas','Bandeja de contenção ou isolamento total da projeção vertical entre frentes','Queda de objetos, queimadura por fagulha',ARRAY['Capacete jugular'],ARRAY['NR-34'],'ALTA'),
('ACIDENTE','Comunicação falha entre equipes',ARRAY['comunicacao','radio','equipe','sinalizacao'],'ADMINISTRATIVA','Canal de rádio dedicado e ponto de parada única','Rádio exclusivo por frente, palavra-código de parada e ponto de encontro definido','Acidente por manobra inesperada',ARRAY[]::text[],ARRAY['NR-01','NR-11'],'MEDIA'),
('GESTAO','Falta de planejamento da tarefa',ARRAY['planejamento','pt','permissao','apr','dds'],'ADMINISTRATIVA','Realizar DDS específico da tarefa e assinar a APR antes do início','DDS com todos os executantes, leitura da APR, checagem de PT e liberação do TST','Execução improvisada, acidente',ARRAY[]::text[],ARRAY['NR-01','NR-34'],'ALTA'),
('GESTAO','Trabalhador sem capacitação válida',ARRAY['treinamento','capacitacao','nr','aso'],'ADMINISTRATIVA','Conferir matriz de treinamento e ASO antes da liberação','Checar validade de NR-33/34/35/11/10 e ASO apto; bloquear quem estiver vencido','Acidente por despreparo, autuação',ARRAY[]::text[],ARRAY['NR-01'],'ALTA'),
('GESTAO','Ferramenta/equipamento sem inspeção',ARRAY['inspecao','ferramenta','checklist','equipamento'],'ADMINISTRATIVA','Inspeção pré-uso com checklist e etiqueta de status','Checklist diário assinado; etiqueta colorida do mês; retirada imediata de item reprovado','Falha de equipamento, acidente',ARRAY[]::text[],ARRAY['NR-12','NR-11'],'MEDIA'),
('GESTAO','Desorganização e resíduos na área',ARRAY['housekeeping','organizacao','residuo','5s','encerramento'],'ADMINISTRATIVA','Housekeeping ao final da tarefa e destinação de resíduos','Recolher cabos, mangueiras e sucata; segregar resíduos; liberar rotas de fuga','Queda, tropeço, incêndio',ARRAY['Luva vaqueta'],ARRAY['NR-18','NR-25'],'MEDIA'),
('GESTAO','Emergência sem resposta definida',ARRAY['emergencia','resgate','brigada','evacuacao'],'ADMINISTRATIVA','Definir plano de resgate e acionamento antes de iniciar','Equipe de resgate para altura/confinado, rota de fuga, ponto de encontro e telefone de emergência na APR','Agravamento de lesão, óbito',ARRAY[]::text[],ARRAY['NR-33','NR-35','NR-01'],'ALTA');

INSERT INTO public.apr_modelos (codigo, nome, categoria, descricao_curta, atividade_descricao, setor_padrao, local_padrao, condicoes_climaticas, observacoes_gerais, exige_pte, ptes_sugeridas, ordem, ativo, riscos) VALUES
('icamento-chapa-garras','Içamento e assentamento de chapa com garras/berço','ICAMENTO','Movimentação de chapa metálica com garras e assentamento em berço.','Içamento de chapa metálica com garras/cintas, transporte por ponte ou guindaste e assentamento em berço/cavalete no pátio.','PRODUÇÃO','Pátio de pré-fabricação','Tempo bom; suspender com vento acima de 40 km/h','Proibida permanência sob carga suspensa. Guiar somente com cabo-guia.', true, ARRAY['ICAMENTO'], 100, true, '[
 {"passo_a_passo":"Inspeção prévia de garras, cintas e manilhas","risco_nome":"Falha de acessório de içamento","risco_categoria":"ACIDENTE","efeitos_danos":"Queda de carga, esmagamento, óbito","probabilidade":2,"severidade":3,"acoes_preventivas":"Inspeção pré-uso registrada; certificado e carga de trabalho visíveis; descarte imediato de item danificado","epis":["Capacete jugular","Luva vaqueta","Botina biqueira composite"],"nrs":["NR-11","NR-12","NR-34"]},
 {"passo_a_passo":"Engate e elevação da chapa","risco_nome":"Queda de carga suspensa","risco_categoria":"ACIDENTE","efeitos_danos":"Esmagamento, óbito","probabilidade":2,"severidade":3,"acoes_preventivas":"Plano de rigging com CG definido; isolamento do raio de ação; sinaleiro exclusivo; ninguém sob a carga","epis":["Capacete jugular","Colete refletivo"],"nrs":["NR-11","NR-34"]},
 {"passo_a_passo":"Guia e posicionamento da chapa","risco_nome":"Prensagem de mãos e pés","risco_categoria":"ACIDENTE","efeitos_danos":"Amputação, fratura","probabilidade":2,"severidade":3,"acoes_preventivas":"Cabo-guia mínimo 2 m; mãos fora da linha de fogo; comunicação por rádio com o operador","epis":["Luva anticorte nível 5","Botina biqueira composite"],"nrs":["NR-11","NR-12"]},
 {"passo_a_passo":"Assentamento no berço/cavalete","risco_nome":"Tombamento da chapa","risco_categoria":"ACIDENTE","efeitos_danos":"Esmagamento, óbito","probabilidade":2,"severidade":3,"acoes_preventivas":"Berço nivelado com calços e travas laterais; soltar a garra somente após estabilização confirmada","epis":["Capacete jugular","Botina biqueira composite"],"nrs":["NR-11","NR-34"]},
 {"passo_a_passo":"Manuseio das bordas da chapa","risco_nome":"Corte por chapa/rebarba","risco_categoria":"ACIDENTE","efeitos_danos":"Corte profundo, laceração","probabilidade":3,"severidade":2,"acoes_preventivas":"Rebarbar bordas antes do manuseio; luva anticorte nível 5 e manguito","epis":["Luva anticorte nível 5","Manguito"],"nrs":["NR-06","NR-12"]},
 {"passo_a_passo":"Permanência no pátio exposto ao sol","risco_nome":"Calor e exposição solar","risco_categoria":"FISICO","efeitos_danos":"Insolação, desidratação","probabilidade":3,"severidade":2,"acoes_preventivas":"Pausa 10 min a cada 50 min em sombra; hidratação; FPS 50","epis":["Chapéu árabe","Óculos UV","Camisa manga longa"],"nrs":["NR-15","NR-21"]}
]'::jsonb),
('hidrojateamento-escada','Hidrojateamento de alta pressão com escada','LIMPEZA','Remoção de resíduo/tinta com jato de água de alta pressão em acesso por escada.','Hidrojateamento de alta pressão para limpeza de superfície/costado, com acesso por escada portátil.','MANUTENÇÃO','Costado / pátio','Suspender sob chuva ou vento forte','Jato nunca direcionado a pessoas. Segundo homem no comando de parada.', true, ARRAY['ALTURA'], 101, true, '[
 {"passo_a_passo":"Montagem e pressurização do conjunto","risco_nome":"Injeção de água em alta pressão","risco_categoria":"ACIDENTE","efeitos_danos":"Injeção dérmica, amputação, infecção grave","probabilidade":2,"severidade":3,"acoes_preventivas":"Pistola com gatilho dead-man; mangueira com capa antichicote; teste hidrostático em dia; despressurizar antes de qualquer ajuste","epis":["Macacão impermeável","Luva para hidrojato","Protetor facial","Perneira"],"nrs":["NR-06","NR-12","NR-34"]},
 {"passo_a_passo":"Acesso e posicionamento na escada","risco_nome":"Queda de altura por escada instável","risco_categoria":"ACIDENTE","efeitos_danos":"Fratura, TCE, óbito","probabilidade":2,"severidade":3,"acoes_preventivas":"Escada amarrada no topo, sapata antiderrapante, ângulo 75°, base em piso firme (nunca areia solta); cinturão com talabarte ancorado acima da cintura","epis":["Cinturão paraquedista","Talabarte duplo com ABS","Capacete jugular"],"nrs":["NR-35","NR-18"]},
 {"passo_a_passo":"Acionamento da pistola","risco_nome":"Coice/reação da pistola","risco_categoria":"ACIDENTE","efeitos_danos":"Perda de equilíbrio, queda, lesão de ombro","probabilidade":3,"severidade":3,"acoes_preventivas":"Operador com dois apoios firmes; jato sempre à frente; segundo homem junto ao comando de parada de emergência","epis":["Cinturão paraquedista","Protetor facial"],"nrs":["NR-12","NR-35"]},
 {"passo_a_passo":"Geração de névoa e respingos","risco_nome":"Névoa contaminada e respingo","risco_categoria":"QUIMICO","efeitos_danos":"Doença respiratória, dermatose, lesão ocular","probabilidade":3,"severidade":2,"acoes_preventivas":"Respirador conforme FISPQ do revestimento; macacão impermeável; trabalhar a favor do vento","epis":["Respirador PFF2","Macacão impermeável","Óculos ampla visão"],"nrs":["NR-06","NR-09","NR-15"]},
 {"passo_a_passo":"Operação contínua do equipamento","risco_nome":"Ruído ocupacional","risco_categoria":"FISICO","efeitos_danos":"PAIR","probabilidade":3,"severidade":2,"acoes_preventivas":"Protetor plug + concha; isolamento da área e afastamento de terceiros","epis":["Protetor auricular plug","Protetor auricular concha"],"nrs":["NR-06","NR-15"]},
 {"passo_a_passo":"Área molhada durante e após a tarefa","risco_nome":"Piso escorregadio e umidade","risco_categoria":"FISICO","efeitos_danos":"Queda de mesmo nível, dermatose","probabilidade":3,"severidade":2,"acoes_preventivas":"Sinalizar piso molhado; drenagem contínua; botina antiderrapante","epis":["Botina antiderrapante","Capa/macacão impermeável"],"nrs":["NR-18"]}
]'::jsonb),
('movimentacao-maquinas-patio','Movimentação de máquinas e equipamentos móveis no pátio','MOVIMENTACAO','Trânsito e manobra de equipamentos móveis em áreas com pedestres.','Deslocamento e manobra de máquinas e equipamentos móveis (empilhadeira, munck, retro, carreta) no pátio do estaleiro.','LOGÍSTICA','Pátio / vias internas','Reduzir velocidade sob chuva','Velocidade máxima 10 km/h. Preferência sempre do pedestre.', false, ARRAY[]::text[], 102, true, '[
 {"passo_a_passo":"Checklist e partida do equipamento","risco_nome":"Falha de equipamento por ausência de inspeção","risco_categoria":"ACIDENTE","efeitos_danos":"Colisão, perda de controle","probabilidade":2,"severidade":3,"acoes_preventivas":"Checklist diário assinado; alarme de ré, giroflex, freios e espelhos operantes; item reprovado bloqueia o uso","epis":["Colete refletivo","Capacete"],"nrs":["NR-11","NR-12"]},
 {"passo_a_passo":"Deslocamento pelas vias do pátio","risco_nome":"Atropelamento de pedestre","risco_categoria":"ACIDENTE","efeitos_danos":"Politrauma, óbito","probabilidade":2,"severidade":3,"acoes_preventivas":"Rotas segregadas de pedestres; velocidade máx. 10 km/h; buzina em cruzamentos; contato visual antes de avançar","epis":["Colete refletivo"],"nrs":["NR-11","NR-12"]},
 {"passo_a_passo":"Manobra em ré ou área confinada","risco_nome":"Ponto cego em manobra","risco_categoria":"ACIDENTE","efeitos_danos":"Atropelamento, colisão","probabilidade":3,"severidade":3,"acoes_preventivas":"Manobra assistida por sinaleiro visível; alarme de ré ativo; parar imediatamente ao perder contato visual","epis":["Colete refletivo","Capacete"],"nrs":["NR-11","NR-12"]},
 {"passo_a_passo":"Transporte de carga com o equipamento","risco_nome":"Queda/tombamento de carga","risco_categoria":"ACIDENTE","efeitos_danos":"Esmagamento, dano patrimonial","probabilidade":2,"severidade":3,"acoes_preventivas":"Carga peiada e dentro da capacidade; garfos baixos em deslocamento; nunca transportar pessoas","epis":["Capacete","Botina biqueira composite"],"nrs":["NR-11"]},
 {"passo_a_passo":"Operação por trabalhador designado","risco_nome":"Operação por não habilitado","risco_categoria":"GESTAO","efeitos_danos":"Acidente grave, autuação","probabilidade":2,"severidade":3,"acoes_preventivas":"Conferir NR-11/NR-12, ASO válido e autorização formal; chave sob controle do encarregado","epis":[],"nrs":["NR-11","NR-12"]},
 {"passo_a_passo":"Abastecimento e parada do equipamento","risco_nome":"Incêndio no abastecimento","risco_categoria":"ACIDENTE","efeitos_danos":"Queimadura, incêndio","probabilidade":1,"severidade":3,"acoes_preventivas":"Motor desligado; extintor próximo; proibido fumar; bandeja de contenção","epis":["Luva nitrílica","Óculos ampla visão"],"nrs":["NR-20","NR-23"]}
]'::jsonb),
('trabalho-ceu-aberto','Trabalho a céu aberto — calor, sol, chuva e descarga atmosférica','AMBIENTAL','Atividades expostas às intempéries no pátio ou no costado.','Execução de atividades a céu aberto sujeitas a calor, radiação solar, chuva e descargas atmosféricas.','SESMT','Pátio / costado','Monitorar boletim meteorológico diariamente','Ao ouvir trovão, paralisar e aguardar 30 min após o último raio.', false, ARRAY[]::text[], 103, true, '[
 {"passo_a_passo":"Planejamento do turno conforme clima","risco_nome":"Sobrecarga térmica (calor)","risco_categoria":"FISICO","efeitos_danos":"Exaustão térmica, cãibras, intermação","probabilidade":3,"severidade":3,"acoes_preventivas":"Regime trabalho-descanso 50/10 em área sombreada; água fresca a até 30 m; monitorar IBUTG; evitar pico das 11h às 14h","epis":["Chapéu árabe","Camisa manga longa"],"nrs":["NR-15","NR-21"]},
 {"passo_a_passo":"Permanência sob sol direto","risco_nome":"Radiação solar UV","risco_categoria":"FISICO","efeitos_danos":"Queimadura, catarata, câncer de pele","probabilidade":3,"severidade":2,"acoes_preventivas":"Tenda/cobertura no posto; protetor solar FPS 50 reaplicado a cada 3 h; óculos com proteção UV","epis":["Óculos UV","Protetor solar FPS 50","Chapéu árabe"],"nrs":["NR-21"]},
 {"passo_a_passo":"Ocorrência de chuva durante a tarefa","risco_nome":"Piso escorregadio e umidade","risco_categoria":"FISICO","efeitos_danos":"Queda de mesmo nível, dermatose","probabilidade":3,"severidade":2,"acoes_preventivas":"Paralisar altura, içamento e serviço elétrico sob chuva; sinalizar e drenar poças","epis":["Capa de chuva","Botina antiderrapante"],"nrs":["NR-18","NR-35"]},
 {"passo_a_passo":"Aproximação de tempestade","risco_nome":"Descarga atmosférica","risco_categoria":"FISICO","efeitos_danos":"Eletrocussão, óbito","probabilidade":1,"severidade":3,"acoes_preventivas":"Alerta meteorológico monitorado; evacuar altura, andaimes e pátio; abrigo em edificação; retorno 30 min após o último raio","epis":[],"nrs":["NR-01","NR-35"]},
 {"passo_a_passo":"Rajadas de vento no pátio","risco_nome":"Vento forte","risco_categoria":"FISICO","efeitos_danos":"Queda de objetos, perda de controle de carga","probabilidade":2,"severidade":3,"acoes_preventivas":"Suspender içamento acima de 40 km/h; peiar materiais leves e lonas","epis":["Capacete jugular"],"nrs":["NR-11","NR-18"]},
 {"passo_a_passo":"Hidratação e monitoramento do time","risco_nome":"Desidratação","risco_categoria":"ERGONOMICO","efeitos_danos":"Cãibra, tontura, queda","probabilidade":3,"severidade":2,"acoes_preventivas":"Ingestão de 200 ml a cada 30 min; observação mútua entre colegas; comunicar mal-estar ao TST","epis":[],"nrs":["NR-17","NR-15"]}
]'::jsonb),
('atividades-simultaneas','Atividades simultâneas incompatíveis (içamento + trabalho a quente)','SIMULTANEAS','Frentes de serviço sobrepostas com risco de interferência.','Execução de atividades simultâneas na mesma projeção vertical/horizontal, como içamento sobre frente de trabalho a quente.','SESMT','Frente de serviço compartilhada','Suspender em baixa visibilidade','Havendo sobreposição não resolvida, uma das frentes deve ser paralisada.', true, ARRAY['ICAMENTO','TRABALHO_QUENTE'], 104, true, '[
 {"passo_a_passo":"Reunião de compatibilização das frentes","risco_nome":"Atividades simultâneas incompatíveis","risco_categoria":"ACIDENTE","efeitos_danos":"Queda de carga sobre pessoas, incêndio, óbito","probabilidade":2,"severidade":3,"acoes_preventivas":"Matriz de compatibilidade no planejamento diário; içamento sobre trabalho a quente proibido; sequenciar ou paralisar uma frente","epis":[],"nrs":["NR-01","NR-11","NR-34"]},
 {"passo_a_passo":"Delimitação das áreas de cada frente","risco_nome":"Invasão do raio de ação","risco_categoria":"ACIDENTE","efeitos_danos":"Esmagamento, atropelamento","probabilidade":3,"severidade":3,"acoes_preventivas":"Isolamento físico da projeção vertical; bandeja de contenção; vigias em cada frente","epis":["Capacete jugular","Colete refletivo"],"nrs":["NR-34","NR-11"]},
 {"passo_a_passo":"Trabalho a quente sob frente de içamento","risco_nome":"Incêndio por fagulha em área compartilhada","risco_categoria":"ACIDENTE","efeitos_danos":"Queimaduras graves, incêndio","probabilidade":2,"severidade":3,"acoes_preventivas":"Manta ignífuga, vigia de fogo e extintor a 5 m; PT de trabalho a quente vinculada à APR","epis":["Uniforme de raspa","Protetor facial"],"nrs":["NR-23","NR-34"]},
 {"passo_a_passo":"Comunicação entre as equipes","risco_nome":"Falha de comunicação","risco_categoria":"GESTAO","efeitos_danos":"Manobra inesperada, acidente","probabilidade":3,"severidade":3,"acoes_preventivas":"Canal de rádio dedicado; palavra-código de parada geral; ponto de parada única com o encarregado","epis":[],"nrs":["NR-01","NR-11"]},
 {"passo_a_passo":"Circulação de terceiros pela área","risco_nome":"Exposição de terceiros","risco_categoria":"ACIDENTE","efeitos_danos":"Lesão por queda de objeto ou fagulha","probabilidade":3,"severidade":3,"acoes_preventivas":"Isolamento com fita e placas; desvio de rota de pedestres; vigia impedindo acesso","epis":["Capacete jugular","Colete refletivo"],"nrs":["NR-34","NR-18"]},
 {"passo_a_passo":"Emergência com frentes sobrepostas","risco_nome":"Resposta a emergência dificultada","risco_categoria":"GESTAO","efeitos_danos":"Agravamento de lesão, óbito","probabilidade":1,"severidade":3,"acoes_preventivas":"Rota de fuga livre para ambas as frentes; plano de resgate definido; ponto de encontro comunicado no DDS","epis":[],"nrs":["NR-01","NR-35","NR-33"]}
]'::jsonb),
('planejamento-encerramento','Planejamento, PT/DDS e encerramento com bloqueio e organização','GESTAO','Etapas de abertura e fechamento seguro de qualquer tarefa.','Planejamento da tarefa, emissão de PT, DDS, capacitação e encerramento com bloqueio (LOTO) e housekeeping.','SESMT','Frente de serviço','Independe do clima','Aplicável como primeiro e último passo de qualquer APR.', false, ARRAY[]::text[], 105, true, '[
 {"passo_a_passo":"Planejamento e liberação da tarefa","risco_nome":"Falta de planejamento da tarefa","risco_categoria":"GESTAO","efeitos_danos":"Execução improvisada, acidente","probabilidade":2,"severidade":3,"acoes_preventivas":"APR lida e assinada por todos; PT emitida quando aplicável; liberação formal do TST antes do início","epis":[],"nrs":["NR-01","NR-34"]},
 {"passo_a_passo":"DDS específico da atividade","risco_nome":"Desconhecimento dos riscos","risco_categoria":"GESTAO","efeitos_danos":"Exposição a risco não percebido","probabilidade":3,"severidade":2,"acoes_preventivas":"DDS com todos os executantes abordando riscos, EPIs, rota de fuga e ponto de encontro; registro de presença","epis":[],"nrs":["NR-01"]},
 {"passo_a_passo":"Conferência de capacitação e saúde","risco_nome":"Trabalhador sem capacitação/ASO válidos","risco_categoria":"GESTAO","efeitos_danos":"Acidente por despreparo, autuação","probabilidade":2,"severidade":3,"acoes_preventivas":"Checar matriz de treinamento (NR-10/11/33/34/35) e ASO apto; bloquear vencidos no sistema","epis":[],"nrs":["NR-01","NR-07"]},
 {"passo_a_passo":"Inspeção de ferramentas e EPIs","risco_nome":"Ferramenta/EPI sem inspeção","risco_categoria":"GESTAO","efeitos_danos":"Falha em uso, lesão","probabilidade":2,"severidade":2,"acoes_preventivas":"Checklist pré-uso com etiqueta do mês; EPI com C.A. válido registrado na ficha","epis":["EPI conforme atividade"],"nrs":["NR-06","NR-12"]},
 {"passo_a_passo":"Encerramento com bloqueio de energias","risco_nome":"Energia residual / partida acidental","risco_categoria":"ACIDENTE","efeitos_danos":"Choque, esmagamento, amputação","probabilidade":2,"severidade":3,"acoes_preventivas":"LOTO com cadeado e etiqueta individual; teste de energia zero; desenergizar e despressurizar antes de sair","epis":["Luva isolante"],"nrs":["NR-10","NR-12"]},
 {"passo_a_passo":"Organização e resíduos ao final","risco_nome":"Desorganização e resíduos na área","risco_categoria":"GESTAO","efeitos_danos":"Queda, tropeço, incêndio","probabilidade":3,"severidade":2,"acoes_preventivas":"Recolher cabos, mangueiras e sucata; segregar resíduos; liberar rotas de fuga; devolver ferramentas","epis":["Luva vaqueta"],"nrs":["NR-18","NR-25"]}
]'::jsonb)
ON CONFLICT (codigo) DO NOTHING;