ALTER TABLE public.catalogo_nrs
  ADD COLUMN IF NOT EXISTS descricao text,
  ADD COLUMN IF NOT EXISTS link_oficial text;

UPDATE public.catalogo_nrs SET descricao = 'Estabelece as disposições gerais, o campo de aplicação, os termos e as definições comuns às Normas Regulamentadoras relativas à segurança e saúde no trabalho. Define as obrigações do empregador e do empregado e institui o Gerenciamento de Riscos Ocupacionais (GRO) e o Programa de Gerenciamento de Riscos (PGR), base do sistema de prevenção em todas as empresas.', link_oficial = 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-1-nr-1' WHERE codigo = 'NR-01';

UPDATE public.catalogo_nrs SET descricao = 'Define a obrigatoriedade, o dimensionamento e as atribuições dos Serviços Especializados em Engenharia de Segurança e em Medicina do Trabalho (SESMT), compostos por médico do trabalho, engenheiro de segurança, enfermeiro do trabalho, técnico de segurança e auxiliar de enfermagem do trabalho. O dimensionamento depende do grau de risco e do número de empregados.', link_oficial = 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-4-nr-4' WHERE codigo = 'NR-04';

UPDATE public.catalogo_nrs SET descricao = 'Regulamenta a Comissão Interna de Prevenção de Acidentes e de Assédio (CIPA), formada paritariamente por representantes do empregador e dos empregados. Tem por objetivo a prevenção de acidentes e doenças decorrentes do trabalho, além de ações de prevenção e combate ao assédio sexual e demais formas de violência no trabalho.', link_oficial = 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-5-nr-5' WHERE codigo = 'NR-05';

UPDATE public.catalogo_nrs SET descricao = 'Trata do Equipamento de Proteção Individual (EPI), de uso pessoal do trabalhador, destinado à proteção contra riscos capazes de ameaçar sua segurança e saúde. Estabelece a obrigação de fornecimento gratuito pelo empregador, com Certificado de Aprovação (CA) válido, treinamento de uso, higienização e substituição quando danificado ou extraviado.', link_oficial = 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-6-nr-6' WHERE codigo = 'NR-06';

UPDATE public.catalogo_nrs SET descricao = 'Estabelece as diretrizes do Programa de Controle Médico de Saúde Ocupacional (PCMSO), de elaboração obrigatória por todos os empregadores. Define exames médicos ocupacionais (admissional, periódico, retorno ao trabalho, mudança de risco, demissional), o Atestado de Saúde Ocupacional (ASO) e ações de promoção e preservação da saúde dos trabalhadores.', link_oficial = 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-7-nr-7' WHERE codigo = 'NR-07';

UPDATE public.catalogo_nrs SET descricao = 'Estabelece requisitos técnicos mínimos para edificações onde se desenvolvem atividades laborais, a fim de garantir segurança e conforto aos trabalhadores. Abrange pé-direito, pisos, paredes, coberturas, escadas, rampas, proteção contra intempéries e demais elementos construtivos dos locais de trabalho.', link_oficial = 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-8-nr-8' WHERE codigo = 'NR-08';

UPDATE public.catalogo_nrs SET descricao = 'Estabelece os requisitos para avaliação e controle das exposições ocupacionais a agentes físicos (ruído, calor, vibrações, radiações), químicos e biológicos. Integra-se ao PGR (NR-01), define limites de exposição, medidas de controle hierárquicas (eliminação, EPC, EPI) e monitoramento contínuo.', link_oficial = 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-9-nr-9' WHERE codigo = 'NR-09';

UPDATE public.catalogo_nrs SET descricao = 'Define requisitos e condições mínimas para garantir a segurança e saúde dos trabalhadores que interagem direta ou indiretamente em instalações elétricas e serviços com eletricidade. Inclui medidas de controle, análise de risco, qualificação/habilitação/capacitação profissional, procedimentos de trabalho, situações de emergência e o curso básico SEP para alta tensão.', link_oficial = 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-10-nr-10' WHERE codigo = 'NR-10';

UPDATE public.catalogo_nrs SET descricao = 'Estabelece os requisitos de segurança a serem observados nas operações de transporte, movimentação, armazenagem e manuseio de materiais — manual ou mecânico. Abrange empilhadeiras, guindastes, transportadores, cabos de aço e o transporte manual de sacos, incluindo a habilitação de operadores de equipamentos motorizados.', link_oficial = 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-11-nr-11' WHERE codigo = 'NR-11';

UPDATE public.catalogo_nrs SET descricao = 'Define referências técnicas, princípios fundamentais e medidas de proteção para garantir saúde e integridade física dos trabalhadores em máquinas e equipamentos de todos os tipos. Trata de arranjo físico, dispositivos de segurança, sistemas de partida e parada, proteções fixas e móveis, manutenção, inspeção e capacitação de operadores.', link_oficial = 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-12-nr-12' WHERE codigo = 'NR-12';

UPDATE public.catalogo_nrs SET descricao = 'Estabelece requisitos para garantir segurança e saúde dos trabalhadores que interagem com caldeiras, vasos de pressão, suas tubulações de interligação e tanques metálicos de armazenamento. Define categorização dos equipamentos, inspeções periódicas, Prontuário, PMTA e capacitação de operadores de caldeira.', link_oficial = 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-13-nr-13' WHERE codigo = 'NR-13';

UPDATE public.catalogo_nrs SET descricao = 'Define atividades e operações insalubres — aquelas que expõem o trabalhador a agentes nocivos à saúde acima dos limites de tolerância. Estabelece limites para ruído contínuo e de impacto, calor, radiações, vibrações, frio, umidade, agentes químicos e biológicos. Gera direito ao adicional de insalubridade em 10%, 20% ou 40%.', link_oficial = 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-15-nr-15' WHERE codigo = 'NR-15';

UPDATE public.catalogo_nrs SET descricao = 'Regulamenta as atividades e operações perigosas — aquelas que, por sua natureza, implicam risco acentuado de explosões, incêndios, choque elétrico, roubos ou outras espécies de violência física, exposição a radiações ionizantes e atividades com motociclista. Garante adicional de periculosidade de 30% sobre o salário-base.', link_oficial = 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-16-nr-16' WHERE codigo = 'NR-16';

UPDATE public.catalogo_nrs SET descricao = 'Estabelece os parâmetros de adaptação das condições de trabalho às características psicofisiológicas dos trabalhadores, visando conforto, segurança e desempenho eficiente. Trata de levantamento de cargas, mobiliário, equipamentos, condições ambientais (iluminação, temperatura, ruído) e organização do trabalho.', link_oficial = 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-17-nr-17' WHERE codigo = 'NR-17';

UPDATE public.catalogo_nrs SET descricao = 'Estabelece diretrizes administrativas, de planejamento e de organização para a implementação de medidas de controle e sistemas preventivos de segurança nos processos, condições e ambientes de trabalho da indústria da construção. Inclui o PGR específico, áreas de vivência, escavações, andaimes, formas e escoramentos.', link_oficial = 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-18-nr-18' WHERE codigo = 'NR-18';

UPDATE public.catalogo_nrs SET descricao = 'Estabelece disposições para o depósito, manuseio e transporte de explosivos, com o objetivo de proteger trabalhadores e a comunidade. Define classificação dos explosivos, condições dos paióis, distâncias de segurança e procedimentos para destruição de explosivos deteriorados.', link_oficial = 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-19-nr-19' WHERE codigo = 'NR-19';

UPDATE public.catalogo_nrs SET descricao = 'Estabelece requisitos mínimos para a gestão da segurança e saúde no trabalho contra fatores de risco em atividades de extração, produção, armazenamento, transferência, manuseio e manipulação de inflamáveis e líquidos combustíveis. Exige Projeto da Instalação, Plano de Resposta a Emergência, Análise de Risco e capacitação específica.', link_oficial = 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-20-nr-20' WHERE codigo = 'NR-20';

UPDATE public.catalogo_nrs SET descricao = 'Estabelece medidas de proteção aos trabalhadores que exercem suas atividades a céu aberto, contra insolação, calor, frio, umidade e ventos inconvenientes. Exige abrigos para refeição e proteção contra intempéries durante as pausas.', link_oficial = 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-21-nr-21' WHERE codigo = 'NR-21';

UPDATE public.catalogo_nrs SET descricao = 'Estabelece as diretrizes para a proteção da segurança e saúde dos trabalhadores em minas subterrâneas e a céu aberto, garimpos e beneficiamento mineral. Inclui ventilação, controle de poeiras, iluminação, escoramento, transporte e plano de emergência.', link_oficial = 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-22-nr-22' WHERE codigo = 'NR-22';

UPDATE public.catalogo_nrs SET descricao = 'Estabelece as medidas de proteção contra incêndios que os locais de trabalho devem dispor: saídas suficientes para evacuação rápida e segura, equipamentos de combate (extintores, hidrantes), sistemas de alarme, treinamento de brigada e exercícios de abandono.', link_oficial = 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-23-nr-23' WHERE codigo = 'NR-23';

UPDATE public.catalogo_nrs SET descricao = 'Define parâmetros sobre condições sanitárias e de conforto: instalações sanitárias, vestiários, refeitórios, cozinhas, alojamentos e fornecimento de água potável. Estabelece áreas mínimas, dimensionamento por número de trabalhadores e padrões de higienização.', link_oficial = 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-24-nr-24' WHERE codigo = 'NR-24';

UPDATE public.catalogo_nrs SET descricao = 'Estabelece as medidas preventivas a serem observadas pelas empresas no destino final adequado dos resíduos industriais — sólidos, líquidos e gasosos — protegendo trabalhadores, comunidade e meio ambiente. Inclui classificação, manuseio, armazenamento, transporte e disposição final.', link_oficial = 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-25-nr-25' WHERE codigo = 'NR-25';

UPDATE public.catalogo_nrs SET descricao = 'Estabelece a padronização das cores utilizadas como sinalização de segurança nos ambientes de trabalho (vermelho, amarelo, verde, azul, etc.), bem como a identificação obrigatória das tubulações industriais por cores e símbolos, conforme o produto transportado e seu risco.', link_oficial = 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-26-nr-26' WHERE codigo = 'NR-26';

UPDATE public.catalogo_nrs SET descricao = 'Disciplina a fiscalização do cumprimento das Normas Regulamentadoras pelos Auditores-Fiscais do Trabalho, define o procedimento de embargo e interdição, gradação das penalidades por descumprimento e o sistema de notificações e autuações.', link_oficial = 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-28-nr-28' WHERE codigo = 'NR-28';

UPDATE public.catalogo_nrs SET descricao = 'Regulamenta a proteção obrigatória contra acidentes e doenças profissionais nos trabalhos portuários realizados a bordo e em terra, bem como nas instalações portuárias. Define obrigações de OGMOs, operadores portuários e tomadores de serviço.', link_oficial = 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-29-nr-29' WHERE codigo = 'NR-29';

UPDATE public.catalogo_nrs SET descricao = 'Aplica-se aos trabalhadores das embarcações comerciais utilizadas no transporte de mercadorias ou passageiros, na navegação marítima, fluvial e lacustre, e em plataformas marítimas e fluviais. Estabelece comissões de segurança a bordo e requisitos de segurança específicos.', link_oficial = 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-30-nr-30' WHERE codigo = 'NR-30';

UPDATE public.catalogo_nrs SET descricao = 'Estabelece os preceitos a serem observados na organização e ambiente de trabalho rural, de forma a tornar compatível o planejamento das atividades agrícolas, pecuárias, silviculturais, de exploração florestal e aquicultura com segurança e saúde. Inclui uso de agrotóxicos, máquinas agrícolas, transporte e moradia.', link_oficial = 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-31-nr-31' WHERE codigo = 'NR-31';

UPDATE public.catalogo_nrs SET descricao = 'Estabelece as diretrizes básicas para a implementação de medidas de proteção à segurança e saúde dos trabalhadores em estabelecimentos de assistência à saúde. Aborda riscos biológicos, químicos, radiações ionizantes, perfurocortantes, vacinação obrigatória e plano de prevenção de acidentes com material biológico.', link_oficial = 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-32-nr-32' WHERE codigo = 'NR-32';

UPDATE public.catalogo_nrs SET descricao = 'Estabelece os requisitos mínimos para identificação de espaços confinados e o reconhecimento, avaliação, monitoramento e controle dos riscos existentes, de forma a garantir permanentemente a segurança e saúde dos trabalhadores que interagem direta ou indiretamente nesses espaços. Exige PET, supervisor de entrada e vigia.', link_oficial = 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-33-nr-33' WHERE codigo = 'NR-33';

UPDATE public.catalogo_nrs SET descricao = 'Estabelece os requisitos mínimos e as medidas de proteção à segurança, à saúde e ao meio ambiente de trabalho nas atividades da indústria de construção, reparação e desmonte naval. Trata de trabalho a quente, em altura, espaço confinado e movimentação de cargas em estaleiros.', link_oficial = 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-34-nr-34' WHERE codigo = 'NR-34';

UPDATE public.catalogo_nrs SET descricao = 'Estabelece os requisitos mínimos para o trabalho em altura — toda atividade executada acima de 2,00 m do nível inferior, onde haja risco de queda. Exige Análise de Risco (AR), Permissão de Trabalho (PT), sistemas de ancoragem, EPI específico (cinto tipo paraquedista, trava-quedas) e capacitação de 8h (básico) ou 40h (supervisor).', link_oficial = 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-35-nr-35' WHERE codigo = 'NR-35';

UPDATE public.catalogo_nrs SET descricao = 'Estabelece os requisitos mínimos para a avaliação, controle e monitoramento dos riscos existentes nas atividades desenvolvidas em empresas de abate e processamento de carnes e derivados de origem animal. Foca em ergonomia, condições ambientais (frio, ruído), pausas e rotatividade de postos.', link_oficial = 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-36-nr-36' WHERE codigo = 'NR-36';

UPDATE public.catalogo_nrs SET descricao = 'Estabelece os requisitos mínimos de segurança, saúde e condições de vivência no trabalho a bordo das plataformas de petróleo, fixas ou móveis, nacionais ou estrangeiras, em operação nas águas jurisdicionais brasileiras. Abrange evacuação, salvamento, helideck e operações simultâneas.', link_oficial = 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-37-nr-37' WHERE codigo = 'NR-37';

UPDATE public.catalogo_nrs SET descricao = 'Estabelece os requisitos de segurança e saúde no trabalho nas atividades de limpeza urbana, coleta, transporte, tratamento e disposição final de resíduos sólidos. Trata de riscos biológicos, perfurocortantes, ergonomia em coleta porta a porta, EPI e vacinação dos garis.', link_oficial = 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-38-nr-38' WHERE codigo = 'NR-38';

COMMENT ON COLUMN public.catalogo_nrs.descricao IS 'Descrição detalhada da NR (objetivo, escopo, principais exigências)';
COMMENT ON COLUMN public.catalogo_nrs.link_oficial IS 'Link da versão vigente no portal gov.br/trabalho-e-emprego';