REVOKE EXECUTE ON FUNCTION public.ajustar_saldo_epi(uuid, integer) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.apply_pending_invite() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.controle_doc_before_insert() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.controle_doc_log_changes() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.current_aal() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.extintor_before_insert() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.gerar_nc_de_checklist() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.gerar_numero_apr() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.gerar_numero_controle_doc() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.gerar_numero_extintor() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.gerar_numero_ordem_producao() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.gerar_numero_tnc() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.has_module_access(uuid, app_module) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.has_role(uuid, app_role) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.is_editor(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.is_moderator(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.is_viewer_or_above(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.log_audit_event() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.mfa_ok() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.peek_proximo_numero_apr() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.registrar_entrega_epi(uuid, text, text, integer) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.registrar_movimentacao_epi(uuid, integer, tipo_movimentacao_epi, text, text, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.requires_mfa(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.snapshot_estoque_epi_monthly() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.sync_attendee_to_matrix() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.sync_training_to_matrix() FROM anon, public;

-- Garante que authenticated e service_role continuam com EXECUTE
GRANT EXECUTE ON FUNCTION public.ajustar_saldo_epi(uuid, integer) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.current_aal() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.gerar_numero_apr() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.gerar_numero_controle_doc() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.gerar_numero_extintor() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.gerar_numero_ordem_producao() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.gerar_numero_tnc() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.has_module_access(uuid, app_module) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, app_role) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_editor(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_moderator(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_viewer_or_above(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.mfa_ok() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.peek_proximo_numero_apr() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.registrar_entrega_epi(uuid, text, text, integer) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.registrar_movimentacao_epi(uuid, integer, tipo_movimentacao_epi, text, text, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.requires_mfa(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.snapshot_estoque_epi_monthly() TO service_role;